# Generated by Django 5.2.8 on 2025-12-01 12:39

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Введение')),
                ('items_per_page', models.PositiveIntegerField(default=9, verbose_name='Кейсов на странице')),
            ],
            options={
                'verbose_name': 'Лента кейсов',
                'verbose_name_plural': 'Лента кейсов',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CaseStudyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Название компании-клиента')),
                ('industry', models.CharField(choices=[('oil-gas', 'Нефтегаз'), ('manufacturing', 'Производство'), ('construction', 'Строительство'), ('government', 'Госсектор'), ('retail', 'Ритейл'), ('logistics', 'Логистика'), ('finance', 'Финансы'), ('healthcare', 'Здравоохранение')], max_length=100, verbose_name='Отрасль')),
                ('project_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата реализации проекта')),
                ('duration', models.CharField(blank=True, max_length=50, verbose_name='Длительность проекта')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Местоположение')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='1-3 предложения для анонса', verbose_name='Краткое описание')),
                ('content', wagtail.fields.StreamField([('description', 0), ('challenge', 1), ('solution', 2), ('results', 5), ('technologies', 7), ('metrics', 11)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'h2', 'h3', 'h4', 'ol', 'ul', 'image', 'embed', 'code', 'blockquote', 'hr', 'document-link', 'superscript', 'strikethrough'], 'label': 'Описание проекта'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'h2', 'h3', 'h4', 'ol', 'ul', 'image', 'embed', 'code', 'blockquote', 'hr', 'document-link', 'superscript', 'strikethrough'], 'label': 'Задача'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'h2', 'h3', 'h4', 'ol', 'ul', 'image', 'embed', 'code', 'blockquote', 'hr', 'document-link', 'superscript', 'strikethrough'], 'label': 'Решение'}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'label': 'Текст результата'}), 4: ('wagtail.blocks.StructBlock', [[('text', 3)]], {'icon': 'success', 'label': 'Результат'}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Результаты '}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Технология'}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Используемые технологии'}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Значение'}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Описание'}), 10: ('wagtail.blocks.StructBlock', [[('value', 8), ('description', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Ключевые метрики'})}, verbose_name='Содержание кейса')),
                ('customer_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Логотип клиента')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Основное изображение')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
            },
            bases=('wagtailcore.page',),
        ),
    ]
