# Generated by Django 5.2.6 on 2025-09-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_casestudyindexpage_delete_casestudiesindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudypage',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя заказчика'),
        ),
        migrations.AlterField(
            model_name='casestudypage',
            name='industry',
            field=models.CharField(blank=True, help_text='Например: Нефтегазовая, Промышленность', max_length=50, verbose_name='Отрасль заказчика'),
        ),
    ]
