# Generated by Django 5.2.6 on 2025-09-17 22:04

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_casestudypage_customer_name_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudyindexpage',
            options={'verbose_name': 'Портфолио кейсов', 'verbose_name_plural': 'Портфолио кейсов'},
        ),
        migrations.AlterModelOptions(
            name='casestudypage',
            options={'verbose_name': 'Кейс', 'verbose_name_plural': 'Кейсы'},
        ),
        migrations.RemoveField(
            model_name='casestudyindexpage',
            name='customer_logo',
        ),
        migrations.RemoveField(
            model_name='casestudyindexpage',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='casestudyindexpage',
            name='items_per_page',
            field=models.PositiveIntegerField(default=9, verbose_name='Кейсов на странице'),
        ),
        migrations.AddField(
            model_name='casestudypage',
            name='duration',
            field=models.CharField(blank=True, max_length=50, verbose_name='Длительность проекта'),
        ),
        migrations.AddField(
            model_name='casestudypage',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='casestudypage',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Основное изображение'),
        ),
        migrations.AddField(
            model_name='casestudypage',
            name='project_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата реализации проекта'),
        ),
        migrations.AlterField(
            model_name='casestudyindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Введение'),
        ),
        migrations.AlterField(
            model_name='casestudypage',
            name='content',
            field=wagtail.fields.StreamField([('description', 0), ('challenge', 1), ('solution', 2), ('results', 3), ('technologies', 5), ('metrics', 9)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание проекта'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Задача'}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Решение'}), 3: ('wagtail.blocks.RichTextBlock', (), {'label': 'Результаты'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Технология'}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Используемые технологии'}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Значение'}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Описание метрики'}), 8: ('wagtail.blocks.StructBlock', [[('value', 6), ('description', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'label': 'Ключевые метрики'})}, verbose_name='Содержание кейса'),
        ),
        migrations.AlterField(
            model_name='casestudypage',
            name='customer_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Логотип клиента'),
        ),
        migrations.AlterField(
            model_name='casestudypage',
            name='customer_name',
            field=models.CharField(max_length=255, verbose_name='Название компании-клиента'),
        ),
        migrations.AlterField(
            model_name='casestudypage',
            name='industry',
            field=models.CharField(choices=[('oil-gas', 'Нефтегаз'), ('manufacturing', 'Производство'), ('construction', 'Строительство'), ('government', 'Госсектор'), ('retail', 'Ритейл'), ('logistics', 'Логистика'), ('finance', 'Финансы'), ('healthcare', 'Здравоохранение')], max_length=100, verbose_name='Отрасль'),
        ),
        migrations.AlterField(
            model_name='casestudypage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='1-3 предложения для анонса', verbose_name='Краткое описание'),
        ),
    ]
