# Generated by Django 5.2.6 on 2025-10-02 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_casestudyindexpage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudyindexpage',
            options={'verbose_name': 'Лента кейсов', 'verbose_name_plural': 'Лента кейсов'},
        ),
    ]
