# Generated by Django 5.2.7 on 2025-10-06 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_casestudyindexpage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudyindexpage',
            options={'verbose_name': 'Портфолио кейсов', 'verbose_name_plural': 'Портфолио кейсов'},
        ),
    ]
