# Generated by Django 5.2.7 on 2025-11-05 12:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_alter_casestudyindexpage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudypage',
            name='content',
            field=wagtail.fields.StreamField([('description', 0), ('challenge', 3), ('solution', 8), ('results', 13), ('technologies', 15), ('metrics', 19)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Описание проекта'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'label': 'Проблема'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Контекст (необязательно)', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('problem', 1), ('context', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Название шага'}), 5: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Описание'}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gear', 'Настройка'), ('code', 'Разработка'), ('database', 'Интеграция'), ('eye', 'Визуализация'), ('check', 'Тестирование'), ('rocket', 'Запуск')], 'label': 'Иконка', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 4), ('description', 5), ('icon', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'label': 'Шаги решения'}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок'}), 10: ('wagtail.blocks.TextBlock', (), {'label': 'Описание'}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('zap', 'Скорость'), ('link', 'Интеграция'), ('eye', 'Визуализация'), ('shield', 'Безопасность'), ('chart', 'Аналитика'), ('check', 'Надёжность')], 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 9), ('description', 10), ('icon', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'label': 'Результаты (карточки)'}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Технология'}), 15: ('wagtail.blocks.ListBlock', (14,), {'label': 'Технологии'}), 16: ('wagtail.blocks.CharBlock', (), {'label': 'Значение'}), 17: ('wagtail.blocks.CharBlock', (), {'label': 'Описание'}), 18: ('wagtail.blocks.StructBlock', [[('value', 16), ('description', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {'label': 'Ключевые метрики'})}, verbose_name='Содержание кейса'),
        ),
        migrations.AlterField(
            model_name='casestudypage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Краткое описание'),
        ),
    ]
