# Generated by Django 5.2.7 on 2025-11-06 06:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_alter_casestudypage_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudypage',
            name='content',
            field=wagtail.fields.StreamField([('description', 0), ('challenge', 1), ('solution', 2), ('results', 3), ('technologies', 5), ('metrics', 9)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание проекта'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Задача'}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Решение'}), 3: ('wagtail.blocks.RichTextBlock', (), {'label': 'Результаты'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Технология'}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Используемые технологии'}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Значение'}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Описание метрики'}), 8: ('wagtail.blocks.StructBlock', [[('value', 6), ('description', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'label': 'Ключевые метрики'})}, verbose_name='Содержание кейса'),
        ),
        migrations.AlterField(
            model_name='casestudypage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='1-3 предложения для анонса', verbose_name='Краткое описание'),
        ),
    ]
