# Generated by Django 5.2.7 on 2025-11-06 07:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_alter_casestudypage_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudypage',
            name='content',
            field=wagtail.fields.StreamField([('description', 0), ('challenge', 8), ('solution', 9), ('results', 14), ('technologies', 16), ('metrics', 20)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'superscript'], 'label': 'Описание проекта'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Простой текст'), ('numbered_list', 'Нумерованный список'), ('bullet_list', 'Список с точками')], 'label': 'Тип элемента'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('filled', 'Закрашенные точки'), ('empty', 'Пустые точки')], 'label': 'Стиль точек (для bullet_list)', 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'label': 'Элемент списка'}), 4: ('wagtail.blocks.ListBlock', (3,), {'label': 'Содержимое'}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение справа', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('type', 1), ('bullet_style', 2), ('content', 4), ('image', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('items', 7)]], {'label': 'Задача'}), 9: ('wagtail.blocks.StructBlock', [[('items', 7)]], {'label': 'Решение'}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок блока'}), 11: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание'}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка (опционально, по умолчанию галочка)', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 10), ('description', 11), ('icon', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'label': 'Результаты (квадратные блоки)'}), 15: ('wagtail.blocks.CharBlock', (), {'label': 'Технология'}), 16: ('wagtail.blocks.ListBlock', (15,), {'label': 'Используемые технологии'}), 17: ('wagtail.blocks.CharBlock', (), {'label': 'Значение'}), 18: ('wagtail.blocks.CharBlock', (), {'label': 'Описание метрики'}), 19: ('wagtail.blocks.StructBlock', [[('value', 17), ('description', 18)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {'label': 'Ключевые метрики'})}, verbose_name='Содержание кейса'),
        ),
    ]
