# Generated by Django 5.2.7 on 2025-11-06 07:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_alter_casestudypage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudypage',
            name='content',
            field=wagtail.fields.StreamField([('description', 0), ('challenge', 1), ('solution', 2), ('results', 3), ('technologies', 5), ('metrics', 9)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'h2', 'h3', 'h4', 'ol', 'ul', 'image', 'embed', 'code', 'blockquote', 'hr', 'document-link', 'superscript', 'strikethrough'], 'label': 'Описание проекта'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'h2', 'h3', 'h4', 'ol', 'ul', 'image', 'embed', 'code', 'blockquote', 'hr', 'document-link', 'superscript', 'strikethrough'], 'label': 'Задача'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'h2', 'h3', 'h4', 'ol', 'ul', 'image', 'embed', 'code', 'blockquote', 'hr', 'document-link', 'superscript', 'strikethrough'], 'label': 'Решение'}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'h2', 'h3', 'h4', 'ol', 'ul', 'image', 'embed', 'code', 'blockquote', 'hr', 'document-link', 'superscript', 'strikethrough'], 'label': 'Результаты'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Технология'}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Используемые технологии'}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Значение'}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Описание'}), 8: ('wagtail.blocks.StructBlock', [[('value', 6), ('description', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'label': 'Ключевые метрики'})}, verbose_name='Содержание кейса'),
        ),
    ]
