# Generated by Django 5.2.7 on 2025-11-17 10:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_alter_casestudypage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudypage',
            name='content',
            field=wagtail.fields.StreamField([('description', 0), ('challenge', 1), ('solution', 2), ('results', 5), ('technologies', 7), ('metrics', 11)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'h2', 'h3', 'h4', 'ol', 'ul', 'image', 'embed', 'code', 'blockquote', 'hr', 'document-link', 'superscript', 'strikethrough'], 'label': 'Описание проекта'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'h2', 'h3', 'h4', 'ol', 'ul', 'image', 'embed', 'code', 'blockquote', 'hr', 'document-link', 'superscript', 'strikethrough'], 'label': 'Задача'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'h2', 'h3', 'h4', 'ol', 'ul', 'image', 'embed', 'code', 'blockquote', 'hr', 'document-link', 'superscript', 'strikethrough'], 'label': 'Решение'}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'label': 'Текст результата'}), 4: ('wagtail.blocks.StructBlock', [[('text', 3)]], {'icon': 'success', 'label': 'Результат'}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Результаты '}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Технология'}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Используемые технологии'}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Значение'}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Описание'}), 10: ('wagtail.blocks.StructBlock', [[('value', 8), ('description', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Ключевые метрики'})}, verbose_name='Содержание кейса'),
        ),
    ]
