# Generated by Django 5.2.6 on 2025-09-13 07:38

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudiesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('customer_name', models.CharField(blank=True, max_length=250, verbose_name='Имя заказчика')),
                ('industry', models.CharField(blank=True, help_text='Например: Нефтегазовая, Промышленность', max_length=100, verbose_name='Отрасль заказчика')),
                ('intro', wagtail.fields.RichTextField(max_length=250, verbose_name='Краткое описание')),
                ('customer_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Логотип заказчика')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CaseStudyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('customer_name', models.CharField(blank=True, max_length=250, verbose_name='Имя заказчика')),
                ('industry', models.CharField(blank=True, help_text='Например: Нефтегазовая, Промышленность', max_length=100, verbose_name='Отрасль заказчика')),
                ('intro', wagtail.fields.RichTextField(max_length=250, verbose_name='Краткое описание')),
                ('content', wagtail.fields.StreamField([('about_customer', 2), ('purpose', 5), ('automation_fields', 9), ('metrics', 16), ('problems', 20), ('progress', 26), ('results', 30), ('image', 31), ('quote', 32)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'О заказчике', 'label': 'Заголовок'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Содержание'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 1)]], {'icon': 'user', 'label': 'О заказчике'}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Цель внедрения', 'label': 'Заголовок'}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Содержание'}), 5: ('wagtail.blocks.StructBlock', [[('title', 3), ('content', 4)]], {'icon': 'target', 'label': 'Цель внедрения'}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Области автоматизации', 'label': 'Заголовок'}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Область'}), 8: ('wagtail.blocks.ListBlock', (7,), {'label': 'Список областей'}), 9: ('wagtail.blocks.StructBlock', [[('title', 6), ('content', 4), ('fields_list', 8)]], {'icon': 'cog', 'label': 'Области автоматизации'}), 10: ('wagtail.blocks.CharBlock', (), {'default': 'Результаты внедрения', 'label': 'Заголовок'}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: 19.6', 'label': 'Значение (%)'}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: сократили расходы', 'label': 'Описание'}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('arrow-up', 'Рост'), ('arrow-down', 'Сокращение')], 'label': 'Тип изменения'}), 14: ('wagtail.blocks.StructBlock', [[('value', 11), ('description', 12), ('icon', 13)]], {'label': 'Метрика'}), 15: ('wagtail.blocks.ListBlock', (14,), {'label': 'Список метрик'}), 16: ('wagtail.blocks.StructBlock', [[('title', 10), ('metrics_list', 15)]], {'icon': 'chart-bar', 'label': 'Метрики эффективности'}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'Проблемы и сложности', 'label': 'Заголовок'}), 18: ('wagtail.blocks.CharBlock', (), {'label': 'Проблема'}), 19: ('wagtail.blocks.ListBlock', (18,), {'label': 'Список проблем'}), 20: ('wagtail.blocks.StructBlock', [[('title', 17), ('content', 4), ('problems_list', 19)]], {'icon': 'warning', 'label': 'Проблемы'}), 21: ('wagtail.blocks.CharBlock', (), {'default': 'Ход реализации', 'label': 'Заголовок'}), 22: ('wagtail.blocks.CharBlock', (), {'label': 'Этап'}), 23: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('stage', 22), ('description', 23)]], {'label': 'Этап'}), 25: ('wagtail.blocks.ListBlock', (24,), {'label': 'Этапы реализации'}), 26: ('wagtail.blocks.StructBlock', [[('title', 21), ('stages', 25)]], {'icon': 'list-ol', 'label': 'Ход реализации'}), 27: ('wagtail.blocks.CharBlock', (), {'default': 'Результаты', 'label': 'Заголовок'}), 28: ('wagtail.blocks.CharBlock', (), {'label': 'Подсистема'}), 29: ('wagtail.blocks.ListBlock', (28,), {'label': 'Внедренные подсистемы'}), 30: ('wagtail.blocks.StructBlock', [[('title', 27), ('content', 4), ('subsystems', 29)]], {'icon': 'check-circle', 'label': 'Результаты'}), 31: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 32: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Цитата'})}, verbose_name='Содержание кейса')),
                ('customer_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Логотип заказчика')),
            ],
            options={
                'verbose_name': 'Кейс внедрения',
                'verbose_name_plural': 'Кейсы внедрений',
            },
            bases=('wagtailcore.page',),
        ),
    ]
