# Generated by Django 5.2.12 on 2026-04-13 10:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicypage',
            name='content',
            field=wagtail.fields.StreamField([('text', 0), ('table', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Текст'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок таблицы', 'required': False}), 2: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 1), ('table', 2)]], {})}, verbose_name='Cодержимое страницы'),
        ),
        migrations.AlterField(
            model_name='privacypolicypage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Старое содержимое страницы'),
        ),
    ]
