# Generated by Django 5.2.12 on 2026-04-17 06:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0003_migrate_body_to_content_and_remove_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypolicypage',
            options={'verbose_name': 'Политика конфиденциальности', 'verbose_name_plural': 'Политика конфиденциальности'},
        ),
        migrations.AlterField(
            model_name='privacypolicypage',
            name='content',
            field=wagtail.fields.StreamField([('text', 0), ('table', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Текст'}), 1: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица'})}, verbose_name='Содержимое страницы'),
        ),
    ]
