# Generated by Django 5.2.6 on 2025-09-13 07:40

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content_blocks',
            field=wagtail.fields.StreamField([('services_section', 3), ('casestudies_section', 6), ('solution_section', 9), ('news_section', 13), ('contacts_section', 19), ('feedback_form_section', 23)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['services.ServicePage']}), 2: ('wagtail.blocks.ListBlock', (1,), {}), 3: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('services', 2)]], {'label': 'Секция предоставляемых услуг компании'}), 4: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['casestudies.CaseStudyPage']}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('casestudies', 5)]], {'label': 'Секция кейсов (внедрений)'}), 7: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['solutions.SolutionPage']}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('solutions', 8)]], {'label': 'Секция решений компании'}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Новостной заголовок'}), 11: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['news.NewsPage']}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('section_title', 10), ('news', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'Контакты', 'label': 'Заголовок секции', 'required': False}), 15: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Показывать карту', 'required': False}), 16: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Вставьте embed код карты из Yandex Maps, Google Maps, ...', 'label': 'Код embed карты', 'required': False}), 17: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Контакты', 'page_type': []}), 18: ('wagtail.blocks.ListBlock', (17,), {'label': 'Выбранные контакты', 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('section_title', 14), ('show_map', 15), ('map_embed', 16), ('contact_items', 18)]], {'label': 'Контакты компании'}), 20: ('wagtail.blocks.CharBlock', (), {'default': 'Свяжитесь с нами', 'label': 'Заголовок формы', 'required': False}), 21: ('wagtail.blocks.TextBlock', (), {'label': 'Описание формы', 'required': False}), 22: ('wagtail.blocks.CharBlock', (), {'default': 'Спасибо! Ваше сообщение отправлено.', 'label': 'Сообщение об успешной отправке', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('form_title', 20), ('form_description', 21), ('success_message', 22)]], {'label': 'Форма обратной связи'})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_background_image',
            field=models.ForeignKey(blank=True, help_text='Рекомендуемый размер: 1920x1080px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фоновое изображение'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_headline',
            field=models.CharField(blank=True, help_text='Основной заголовок в верхней секции', max_length=100, null=True, verbose_name='Главный заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subheadline',
            field=models.CharField(blank=True, help_text='Дополнительный текст пол основным заголовком', max_length=250, verbose_name='Подзаголовок'),
        ),
    ]
