# Generated by Django 5.2.6 on 2025-09-16 11:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_content_blocks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_background_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_headline',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_subheadline',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_carousel',
            field=wagtail.fields.StreamField([('carousel', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Подзаголовок', 'max_length': 250, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Рекомендуемый размер: 1920x1080px', 'label': 'Фоновое изображение', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Подробнее', 'label': 'Текст кнопки', 'required': True}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка кнопки', 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('headline', 0), ('subheadline', 1), ('background_image', 2), ('button_text', 3), ('button_link', 4)]], {'label': 'Слайд'}), 6: ('wagtail.blocks.StreamBlock', [[('slide', 5)]], {})}, help_text='Добавьте слайды для карусели в верхней секции', verbose_name='Карусель секции hero'),
        ),
    ]
