# Generated by Django 5.2.6 on 2025-09-16 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homepage_hero_background_image_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_carousel',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_background_image',
            field=models.ForeignKey(blank=True, help_text='Рекомендуемый размер: 1920x1080px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фоновое изображение'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_headline',
            field=models.CharField(blank=True, help_text='Основной заголовок в верхней секции', max_length=100, null=True, verbose_name='Главный заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subheadline',
            field=models.CharField(blank=True, help_text='Дополнительный текст под основным заголовком', max_length=250, verbose_name='Подзаголовок'),
        ),
    ]
