# Generated by Django 5.2.6 on 2025-09-16 12:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_background_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_headline',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_subheadline',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='logo',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_slides',
            field=wagtail.fields.StreamField([('slide', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок слайда', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Подзаголовок слайда', 'max_length': 250, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Рекомендуемый размер: 1920x1080px', 'label': 'Фоновое изображение', 'required': True}), 3: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка слайда', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('headline', 0), ('subheadline', 1), ('background_image', 2), ('link', 3)]], {'label': 'Слайд'})}, verbose_name='Слайды героя'),
        ),
    ]
