# Generated by Django 5.2.6 on 2025-09-17 05:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homepage_content_blocks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Главная страница', 'verbose_name_plural': 'Главные страницы'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='achievements_section',
            field=wagtail.fields.StreamField([('achievements', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Числовое значение или текст', 'max_length': 10, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Заголовок достижения', 'max_length': 100, 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Описание', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('value', 0), ('title', 1), ('description', 2)]], {})}, verbose_name='Дополнительные достижения'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats_section',
            field=wagtail.fields.StreamField([('stats', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Название иконки из lucide-react (например, 'Calendar')", 'required': True}), 1: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Числовое значение', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'default': '+', 'help_text': "Суффикс (например, '+' или '%')", 'max_length': 10, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Краткое название', 'max_length': 100, 'required': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Описание достижения', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('icon', 0), ('value', 1), ('suffix', 2), ('label', 3), ('description', 4)]], {})}, verbose_name='Статистика'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content_blocks',
            field=wagtail.fields.StreamField([('services_section', 3), ('casestudies_section', 6), ('solution_section', 9), ('news_section', 13), ('contacts_section', 19), ('feedback_form_section', 23)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['services.ServicePage']}), 2: ('wagtail.blocks.ListBlock', (1,), {}), 3: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('services', 2)]], {'label': 'Предоставляемые услуги компании'}), 4: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['cases.CaseStudyPage']}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('cases', 5)]], {'label': 'Кейсы (внедрения)'}), 7: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['solutions.SolutionPage']}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('solutions', 8)]], {'label': 'Решения'}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Новостной заголовок'}), 11: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['news.NewsIndexPage']}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('section_title', 10), ('news', 12)]], {'label': 'Новости'}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'Контакты', 'label': 'Заголовок секции', 'required': False}), 15: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Показывать карту', 'required': False}), 16: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Вставьте embed код карты из Yandex Maps, Google Maps, ...', 'label': 'Код embed карты', 'required': False}), 17: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Контакты', 'page_type': []}), 18: ('wagtail.blocks.ListBlock', (17,), {'label': 'Выбранные контакты', 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('section_title', 14), ('show_map', 15), ('map_embed', 16), ('contact_items', 18)]], {'label': 'Контакты компании'}), 20: ('wagtail.blocks.CharBlock', (), {'default': 'Свяжитесь с нами', 'label': 'Заголовок формы', 'required': False}), 21: ('wagtail.blocks.TextBlock', (), {'label': 'Описание формы', 'required': False}), 22: ('wagtail.blocks.CharBlock', (), {'default': 'Спасибо! Ваше сообщение отправлено.', 'label': 'Сообщение об успешной отправке', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('form_title', 20), ('form_description', 21), ('success_message', 22)]], {'label': 'Форма обратной связи'})}),
        ),
    ]
