# Generated by Django 5.2.6 on 2025-09-17 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homepage_options_homepage_achievements_section_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='stats_section',
        ),
        migrations.CreateModel(
            name='StatisticPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('value', models.IntegerField(default=0, help_text='Числовое значение')),
                ('suffix', models.CharField(blank=True, default='+', help_text="Суффикс (например, '+' или '%')", max_length=10)),
                ('label', models.CharField(help_text='Краткое название', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Описание достижения')),
                ('icon', models.ForeignKey(blank=True, help_text='Выберите изображение для иконки (рекомендуемый размер: 50x50px)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Статистика',
            },
            bases=('wagtailcore.page',),
        ),
    ]
