# Generated by Django 5.2.6 on 2025-09-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_homepage_stats_section_statisticpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statisticpage',
            options={'verbose_name': 'Статистика и достижения'},
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='achievements_section',
        ),
        migrations.AddField(
            model_name='statisticpage',
            name='add_description',
            field=models.TextField(blank=True, help_text='Описание дополнительного достижения'),
        ),
        migrations.AddField(
            model_name='statisticpage',
            name='add_title',
            field=models.CharField(blank=True, help_text='Заголовок дополнительного достижения', max_length=100),
        ),
        migrations.AddField(
            model_name='statisticpage',
            name='add_value',
            field=models.CharField(blank=True, help_text='Числовое значение или текст для дополнительного достижения', max_length=10),
        ),
    ]
