# Generated by Django 5.2.6 on 2025-09-17 10:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homepage_achievements_delete_statisticpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content_blocks',
            field=wagtail.fields.StreamField([('services_section', 3), ('casestudies_section', 6), ('solution_section', 9), ('news_section', 16), ('contacts_section', 22), ('feedback_form_section', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['services.ServicePage']}), 2: ('wagtail.blocks.ListBlock', (1,), {}), 3: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('services', 2)]], {'label': 'Предоставляемые услуги компании'}), 4: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['cases.CaseStudyPage']}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('cases', 5)]], {'label': 'Кейсы (внедрения)'}), 7: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['solutions.SolutionPage']}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('solutions', 8)]], {'label': 'Решения'}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Новостной заголовок'}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Рекомендуемый размер: 400x300px', 'label': 'Изображение', 'required': True}), 12: ('wagtail.blocks.DateBlock', (), {'label': 'Дата публикации', 'required': True}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок новости', 'max_length': 100, 'required': True}), 14: ('wagtail.blocks.StructBlock', [[('image', 11), ('date', 12), ('headline', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('section_title', 10), ('news', 15)]], {'label': 'Новости'}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'Контакты', 'label': 'Заголовок секции', 'required': False}), 18: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Показывать карту', 'required': False}), 19: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Вставьте embed код карты из Yandex Maps, Google Maps, ...', 'label': 'Код embed карты', 'required': False}), 20: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Контакты', 'page_type': []}), 21: ('wagtail.blocks.ListBlock', (20,), {'label': 'Выбранные контакты', 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('section_title', 17), ('show_map', 18), ('map_embed', 19), ('contact_items', 21)]], {'label': 'Контакты компании'}), 23: ('wagtail.blocks.CharBlock', (), {'default': 'Свяжитесь с нами', 'label': 'Заголовок формы', 'required': False}), 24: ('wagtail.blocks.TextBlock', (), {'label': 'Описание формы', 'required': False}), 25: ('wagtail.blocks.CharBlock', (), {'default': 'Спасибо! Ваше сообщение отправлено.', 'label': 'Сообщение об успешной отправке', 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('form_title', 23), ('form_description', 24), ('success_message', 25)]], {'label': 'Форма обратной связи'})}),
        ),
    ]
