# Generated by Django 5.2.6 on 2025-09-17 10:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_homepage_content_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content_blocks',
            field=wagtail.fields.StreamField([('services_section', 3), ('casestudies_section', 6), ('solution_section', 9), ('news_section', 12), ('contacts_section', 18), ('feedback_form_section', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['services.ServicePage']}), 2: ('wagtail.blocks.ListBlock', (1,), {}), 3: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('services', 2)]], {'label': 'Предоставляемые услуги компании'}), 4: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['cases.CaseStudyPage']}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('cases', 5)]], {'label': 'Кейсы (внедрения)'}), 7: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['solutions.SolutionPage']}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('solutions', 8)]], {'label': 'Решения'}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции новостей', 'max_length': 100, 'required': True}), 11: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'label': 'Количество новостей для показа', 'max_value': 12, 'min_value': 1}), 12: ('wagtail.blocks.StructBlock', [[('title', 10), ('show_count', 11)]], {'label': 'Блок новостей'}), 13: ('wagtail.blocks.CharBlock', (), {'default': 'Контакты', 'label': 'Заголовок секции', 'required': False}), 14: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Показывать карту', 'required': False}), 15: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Вставьте embed код карты из Yandex Maps, Google Maps, ...', 'label': 'Код embed карты', 'required': False}), 16: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Контакты', 'page_type': []}), 17: ('wagtail.blocks.ListBlock', (16,), {'label': 'Выбранные контакты', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('section_title', 13), ('show_map', 14), ('map_embed', 15), ('contact_items', 17)]], {'label': 'Контакты компании'}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'Свяжитесь с нами', 'label': 'Заголовок формы', 'required': False}), 20: ('wagtail.blocks.TextBlock', (), {'label': 'Описание формы', 'required': False}), 21: ('wagtail.blocks.CharBlock', (), {'default': 'Спасибо! Ваше сообщение отправлено.', 'label': 'Сообщение об успешной отправке', 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('form_title', 19), ('form_description', 20), ('success_message', 21)]], {'label': 'Форма обратной связи'})}),
        ),
    ]
