# Generated by Django 5.2.6 on 2025-09-17 12:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_homepage_content_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content_blocks',
            field=wagtail.fields.StreamField([('services_section', 3), ('casestudies_section', 8), ('solution_section', 11), ('news_section', 14), ('contacts_section', 20), ('feedback_form_section', 24)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['services.ServicePage']}), 2: ('wagtail.blocks.ListBlock', (1,), {}), 3: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('services', 2)]], {'label': 'Предоставляемые услуги компании'}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Наши кейсы', 'label': 'Заголовок секции', 'required': True}), 5: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Кейс', 'page_type': ['cases.CaseStudyPage']}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Выберите кейсы для отображения', 'max_num': 6, 'min_num': 1}), 7: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': "Показывать кнопку 'Все кейсы'", 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('section_title', 4), ('cases', 6), ('show_view_all_button', 7)]], {'label': 'Кейсы (внедрения)'}), 9: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['solutions.SolutionPage']}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('solutions', 10)]], {'label': 'Решения'}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции новостей', 'max_length': 100, 'required': True}), 13: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'label': 'Количество новостей для показа', 'max_value': 12, 'min_value': 1}), 14: ('wagtail.blocks.StructBlock', [[('title', 12), ('show_count', 13)]], {'label': 'Блок новостей'}), 15: ('wagtail.blocks.CharBlock', (), {'default': 'Контакты', 'label': 'Заголовок секции', 'required': False}), 16: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Показывать карту', 'required': False}), 17: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Вставьте embed код карты из Yandex Maps, Google Maps, ...', 'label': 'Код embed карты', 'required': False}), 18: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Контакты', 'page_type': []}), 19: ('wagtail.blocks.ListBlock', (18,), {'label': 'Выбранные контакты', 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('section_title', 15), ('show_map', 16), ('map_embed', 17), ('contact_items', 19)]], {'label': 'Контакты компании'}), 21: ('wagtail.blocks.CharBlock', (), {'default': 'Свяжитесь с нами', 'label': 'Заголовок формы', 'required': False}), 22: ('wagtail.blocks.TextBlock', (), {'label': 'Описание формы', 'required': False}), 23: ('wagtail.blocks.CharBlock', (), {'default': 'Спасибо! Ваше сообщение отправлено.', 'label': 'Сообщение об успешной отправке', 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('form_title', 21), ('form_description', 22), ('success_message', 23)]], {'label': 'Форма обратной связи'})}),
        ),
    ]
