# Generated by Django 5.2.6 on 2025-09-17 12:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_homepage_content_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content_blocks',
            field=wagtail.fields.StreamField([('services_section', 3), ('casestudies_section', 10), ('solution_section', 13), ('news_section', 16), ('contacts_section', 22), ('feedback_form_section', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['services.ServicePage']}), 2: ('wagtail.blocks.ListBlock', (1,), {}), 3: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('services', 2)]], {'label': 'Предоставляемые услуги компании'}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Кейсы и проекты', 'label': 'Заголовок секции', 'required': True}), 5: ('wagtail.blocks.TextBlock', (), {'default': 'Более 500 успешно реализованных проектов автоматизации для предприятий различных отраслей и масштабов.', 'label': 'Описание секции', 'required': False}), 6: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Кейс', 'page_type': ['cases.CaseStudyPage']}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Выберите кейсы для отображения', 'max_num': 12, 'min_num': 3}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Показывать фильтры по отраслям', 'required': False}), 9: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': "Показывать кнопку 'Все кейсы'", 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('section_title', 4), ('section_description', 5), ('cases', 7), ('show_filters', 8), ('show_view_all_button', 9)]], {'label': 'Кейсы (внедрения)'}), 11: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['solutions.SolutionPage']}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('solutions', 12)]], {'label': 'Решения'}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции новостей', 'max_length': 100, 'required': True}), 15: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'label': 'Количество новостей для показа', 'max_value': 12, 'min_value': 1}), 16: ('wagtail.blocks.StructBlock', [[('title', 14), ('show_count', 15)]], {'label': 'Блок новостей'}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'Контакты', 'label': 'Заголовок секции', 'required': False}), 18: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Показывать карту', 'required': False}), 19: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Вставьте embed код карты из Yandex Maps, Google Maps, ...', 'label': 'Код embed карты', 'required': False}), 20: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Контакты', 'page_type': []}), 21: ('wagtail.blocks.ListBlock', (20,), {'label': 'Выбранные контакты', 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('section_title', 17), ('show_map', 18), ('map_embed', 19), ('contact_items', 21)]], {'label': 'Контакты компании'}), 23: ('wagtail.blocks.CharBlock', (), {'default': 'Свяжитесь с нами', 'label': 'Заголовок формы', 'required': False}), 24: ('wagtail.blocks.TextBlock', (), {'label': 'Описание формы', 'required': False}), 25: ('wagtail.blocks.CharBlock', (), {'default': 'Спасибо! Ваше сообщение отправлено.', 'label': 'Сообщение об успешной отправке', 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('form_title', 23), ('form_description', 24), ('success_message', 25)]], {'label': 'Форма обратной связи'})}),
        ),
    ]
