# Generated by Django 5.2.6 on 2025-09-17 12:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_homepage_content_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content_blocks',
            field=wagtail.fields.StreamField([('services_section', 3), ('casestudies_section', 10), ('solution_section', 13), ('news_section', 17), ('contacts_section', 21), ('feedback_form_section', 24)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['services.ServicePage']}), 2: ('wagtail.blocks.ListBlock', (1,), {}), 3: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('services', 2)]], {'label': 'Предоставляемые услуги компании'}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Кейсы и проекты', 'label': 'Заголовок секции', 'required': True}), 5: ('wagtail.blocks.TextBlock', (), {'default': 'Более 500 успешно реализованных проектов автоматизации для предприятий различных отраслей и масштабов.', 'label': 'Описание секции', 'required': False}), 6: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Кейс', 'page_type': ['cases.CaseStudyPage']}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Выберите кейсы для отображения', 'max_num': 12, 'min_num': 3}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Показывать фильтры по отраслям', 'required': False}), 9: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': "Показывать кнопку 'Все кейсы'", 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('section_title', 4), ('section_description', 5), ('cases', 7), ('show_filters', 8), ('show_view_all_button', 9)]], {'label': 'Кейсы (внедрения)'}), 11: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['solutions.SolutionPage']}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('solutions', 12)]], {'label': 'Решения'}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Новостной заголовок'}), 15: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['news.NewsPage']}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.StructBlock', [[('section_title', 14), ('news', 16)]], {'label': 'Новости'}), 18: ('wagtail.blocks.TextBlock', (), {'label': 'Адрес'}), 19: ('wagtail.blocks.CharBlock', (), {'label': 'Телефон'}), 20: ('wagtail.blocks.CharBlock', (), {'label': 'Email'}), 21: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('address', 18), ('phone', 19), ('email', 20)]], {'label': 'Контакты компании'}), 22: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок формы'}), 23: ('wagtail.blocks.CharBlock', (), {'default': 'Отправить', 'label': 'Текст кнопки'}), 24: ('wagtail.blocks.StructBlock', [[('section_title', 22), ('button_text', 23)]], {'label': 'Форма обратной связи'})}),
        ),
    ]
