# Generated by Django 5.2.6 on 2025-09-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_homepage_content_blocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='content_blocks',
        ),
    ]
