# Generated by Django 5.2.6 on 2025-09-18 19:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_certificatespage_achievement_certificate_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_image',
        ),
        migrations.RemoveField(
            model_name='certificatespage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='logo',
        ),
        migrations.AddField(
            model_name='homepage',
            name='awards',
            field=wagtail.fields.StreamField([('achievement', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название достижения', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание достижения', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {})}, verbose_name='Награды и достижения'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='case_study_section',
            field=wagtail.fields.StreamField([('case_study', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Кейсы и проекты', 'label': 'Заголовок секции', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'default': 'Более 500 успешно реализованных проектов автоматизации для предприятий различных отраслей и масштабов.', 'label': 'Описание секции', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Кейс', 'page_type': ['cases.CaseStudyPage']}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Выберите кейсы для отображения', 'max_num': 12, 'min_num': 3}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Показывать фильтры по отраслям', 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': "Показывать кнопку 'Все кейсы'", 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('section_description', 1), ('cases', 3), ('show_filters', 4), ('show_view_all_button', 5)]], {})}, verbose_name='Секция кейсов'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='certificates',
            field=wagtail.fields.StreamField([('certificate', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название сертификата', 'max_length': 200, 'required': True}), 1: ('wagtail.blocks.StructBlock', [[('title', 0)]], {})}, verbose_name='Сертификаты'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partners',
            field=wagtail.fields.StreamField([('partner', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название партнёра', 'max_length': 100, 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Рекомендуемый размер: 200x200px', 'label': 'Логотип партнёра', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Статус партнёра', 'max_length': 100, 'required': True}), 3: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание партнёра', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('logo', 1), ('status', 2), ('description', 3)]], {})}, verbose_name='Партнёры'),
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='CertificatesPage',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
