# Generated by Django 5.2.6 on 2025-09-22 11:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_certificate_certificate_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header_section',
            field=wagtail.fields.StreamField([('header', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок слайда', 'max_length': 500, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Подзаголовок слайда', 'max_length': 250, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Рекомендуемый размер: 1920x1080px', 'label': 'Фоновое изображение', 'required': True}), 3: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка слайда', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('headline', 0), ('subheadline', 1), ('background_image', 2), ('link', 3)]], {}), 5: ('wagtail.blocks.StreamBlock', [[('slide', 4)]], {'label': 'Слайды', 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 50, 'required': True}), 7: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка кнопки', 'required': True}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Вторичная кнопка', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('text', 6), ('url', 7), ('is_secondary', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'label': 'Кнопки', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('slides', 5), ('buttons', 10)]], {'label': 'Header секция'})}, verbose_name='Header секция'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_slides',
            field=wagtail.fields.StreamField([('slide', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок слайда', 'max_length': 500, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Подзаголовок слайда', 'max_length': 250, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Рекомендуемый размер: 1920x1080px', 'label': 'Фоновое изображение', 'required': True}), 3: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка слайда', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('headline', 0), ('subheadline', 1), ('background_image', 2), ('link', 3)]], {'label': 'Слайд'})}, verbose_name='Слайды героя'),
        ),
    ]
