# Generated by Django 5.2.6 on 2025-09-22 11:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_homepage_header_section_alter_homepage_hero_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='partnership_section',
            field=wagtail.fields.StreamField([('partnership', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции', 'max_length': 500, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Подзаголовок секции', 'max_length': 250, 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Рекомендуемый размер: 54x16px', 'label': 'Логотип партнёра', 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка на партнёра', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('logo', 2), ('link', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'help_text': 'Добавьте до 6 логотипов', 'label': 'Логотипы партнёров', 'max_num': 6, 'min_num': 1}), 6: ('wagtail.blocks.StructBlock', [[('headline', 0), ('subheadline', 1), ('logos', 5)]], {'label': 'Секция партнёрств'})}, verbose_name='Секция партнёрств'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header_section',
            field=wagtail.fields.StreamField([('header', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок слайда', 'max_length': 500, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Подзаголовок слайда', 'max_length': 250, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Рекомендуемый размер: 1920x1080px', 'label': 'Изображение', 'required': True}), 3: ('wagtail.blocks.ListBlock', (2,), {'help_text': 'Добавьте до 3 изображений для разных видов: фон, команда, индивидуальное использование', 'label': 'Изображения слайда (до 3)', 'max_num': 3, 'min_num': 1}), 4: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка слайда', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('headline', 0), ('subheadline', 1), ('images', 3), ('link', 4)]], {}), 6: ('wagtail.blocks.StreamBlock', [[('slide', 5)]], {'label': 'Слайды', 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 50, 'required': True}), 8: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка кнопки', 'required': True}), 9: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Вторичная кнопка', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('text', 7), ('url', 8), ('is_secondary', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Кнопки', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('slides', 6), ('buttons', 11)]], {'label': 'Header секция'})}, verbose_name='Header секция'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_slides',
            field=wagtail.fields.StreamField([('slide', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок слайда', 'max_length': 500, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Подзаголовок слайда', 'max_length': 250, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Рекомендуемый размер: 1920x1080px', 'label': 'Изображение', 'required': True}), 3: ('wagtail.blocks.ListBlock', (2,), {'help_text': 'Добавьте до 3 изображений для разных видов: фон, команда, индивидуальное использование', 'label': 'Изображения слайда (до 3)', 'max_num': 3, 'min_num': 1}), 4: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка слайда', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('headline', 0), ('subheadline', 1), ('images', 3), ('link', 4)]], {'label': 'Слайд'})}, verbose_name='Слайды героя'),
        ),
    ]
