# Generated by Django 5.2.6 on 2025-09-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_faqitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='eyebrow',
            field=models.CharField(blank=True, help_text='Подзаголовок над основным заголовком', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading',
            field=models.CharField(blank=True, help_text='Основной заголовок', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subheading',
            field=models.TextField(blank=True, help_text='Подзаголовок или описание'),
        ),
    ]
