# Generated by Django 5.2.6 on 2025-09-25 07:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_homepage_eyebrow_homepage_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('hero', 2), ('services_section', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('image', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции услуг', 'max_length': 100, 'required': True}), 4: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'label': 'Количество услуг для показа', 'max_value': 12, 'min_value': 1}), 5: ('wagtail.blocks.StructBlock', [[('title', 3), ('show_count', 4)]], {})}, verbose_name='Секции страницы'),
        ),
    ]
