# Generated by Django 5.2.7 on 2025-10-06 10:38

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_homepage_content'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('question', models.CharField(help_text='Введите вопрос', max_length=255, verbose_name='Вопрос')),
                ('answer', wagtail.fields.RichTextField(help_text='Подробный ответ на вопрос', verbose_name='Ответ')),
                ('category', models.CharField(blank=True, help_text='Например: Общие вопросы, Технические вопросы и т.д.', max_length=100, verbose_name='Категория')),
                ('is_featured', models.BooleanField(default=False, help_text='Отображать в списке популярных вопросов', verbose_name='Популярный вопрос')),
                ('order', models.IntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'Вопросы-ответы',
                'ordering': ['order', 'question'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
