# Generated by Django 5.2.7 on 2025-10-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_faqpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqpage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='faqpage',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='faqpage',
            name='eyebrow',
            field=models.CharField(blank=True, help_text='Текст над основным заголовком', max_length=255, verbose_name='Надзаголовок'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='heading',
            field=models.CharField(blank=True, help_text='Главный заголовок секции FAQ', max_length=255, verbose_name='Основной заголовок'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='subheading',
            field=models.TextField(blank=True, help_text='Описание под заголовком', verbose_name='Подзаголовок'),
        ),
    ]
