# Generated by Django 5.2.7 on 2025-10-06 10:55

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_faqpage_category_remove_faqpage_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqpage',
            options={'verbose_name': 'Страница FAQ', 'verbose_name_plural': 'Страницы FAQ'},
        ),
        migrations.RemoveField(
            model_name='faqpage',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='faqpage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='faqpage',
            name='question',
        ),
        migrations.AddField(
            model_name='faqpage',
            name='faq_items',
            field=wagtail.fields.StreamField([('faq', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Вопрос', 'max_length': 255, 'required': True})}, verbose_name='Вопросы и ответы'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='eyebrow',
            field=models.CharField(blank=True, max_length=255, verbose_name='Надзаголовок'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Основной заголовок'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='subheading',
            field=models.TextField(blank=True, verbose_name='Подзаголовок'),
        ),
    ]
