# Generated by Django 5.2.7 on 2025-10-06 11:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_faqpage_options_remove_faqpage_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqpage',
            name='faq_items',
            field=wagtail.fields.StreamField([('faq', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Вопрос', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Ответ', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {'icon': 'help', 'label': 'Вопрос-ответ'})}, verbose_name='Вопросы и ответы'),
        ),
    ]
