# Generated by Django 5.2.7 on 2025-10-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_faqpage_faq_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='FAQItem',
        ),
        migrations.DeleteModel(
            name='FAQPage',
        ),
    ]
