# Generated by Django 5.2.7 on 2025-10-14 08:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_faqpage_page_ptr_delete_faqitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='location_section',
            field=wagtail.fields.StreamField([('location', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название города или страны', 'max_length': 100, 'verbose_name': 'Название локации'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Рекомендуемый размер: 1920x1080px', 'label': 'Изображение локации', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('image', 1)]], {'label': 'Секция Локации'})}, verbose_name='Секция Локации'),
        ),
    ]
