# Generated by Django 5.2.7 on 2025-10-14 08:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_homepage_location_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='location_section',
        ),
        migrations.AddField(
            model_name='homepage',
            name='global_presence',
            field=wagtail.fields.StreamField([('presence', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Глобальное присутствие', 'label': 'Заголовок', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Рекомендуемый размер: квадратное или 1x1', 'label': 'Изображение для локации', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('image', 1)]], {})}, verbose_name="Блок 'Глобальное присутствие'"),
        ),
    ]
