# Generated by Django 5.2.7 on 2025-10-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_homepage_global_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='eyebrow',
            field=models.CharField(blank=True, help_text='Подзаголовок над основным заголовком'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='heading',
            field=models.CharField(blank=True, help_text='Основной заголовок'),
        ),
    ]
