# Generated by Django 5.2.7 on 2025-10-28 07:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_homepage_header_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='case_study_section',
            field=wagtail.fields.StreamField([('case_study', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Кейсы и проекты', 'label': 'Заголовок секции', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'default': 'Более 500 успешно реализованных проектов автоматизации для предприятий различных отраслей и масштабов.', 'features': ['bold', 'italic', 'ol', 'ul', 'link', 'superscript'], 'label': 'Описание секции', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Кейс', 'page_type': ['cases.CaseStudyPage']}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Выберите кейсы для отображения', 'max_num': 12, 'min_num': 3}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Показывать фильтры по отраслям', 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': "Показывать кнопку 'Все кейсы'", 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('section_description', 1), ('cases', 3), ('show_filters', 4), ('show_view_all_button', 5)]], {})}, verbose_name='Секция кейсов'),
        ),
    ]
