# Generated by Django 5.2.7 on 2025-10-28 07:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_homepage_case_study_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='case_study_section',
            field=wagtail.fields.StreamField([('case_study', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Кейсы и проекты', 'label': 'Заголовок секции', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'default': 'Более 500 успешно реализованных проектов автоматизации для предприятий различных отраслей и масштабов.', 'label': 'Описание секции', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Кейс', 'page_type': ['cases.CaseStudyPage']}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Выберите кейсы для отображения', 'max_num': 12, 'min_num': 3}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Показывать фильтры по отраслям', 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': "Показывать кнопку 'Все кейсы'", 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('section_description', 1), ('cases', 3), ('show_filters', 4), ('show_view_all_button', 5)]], {})}, verbose_name='Секция кейсов'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header_section',
            field=wagtail.fields.StreamField([('header', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок слайда', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link', 'superscript'], 'label': 'Подзаголовок слайда', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Рекомендуемый размер: 1920x1080px', 'label': 'Изображение', 'required': True}), 3: ('wagtail.blocks.ListBlock', (2,), {'help_text': 'Добавьте до 3 изображений для разных видов: фон, команда, индивидуальное использование', 'label': 'Изображения слайда (до 3)', 'max_num': 3, 'min_num': 1}), 4: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка слайда', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('headline', 0), ('subheadline', 1), ('images', 3), ('link', 4)]], {}), 6: ('wagtail.blocks.StreamBlock', [[('slide', 5)]], {'label': 'Слайды', 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 50, 'required': True}), 8: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка кнопки', 'required': True}), 9: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Вторичная кнопка', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('text', 7), ('url', 8), ('is_secondary', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Кнопки', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('slides', 6), ('buttons', 11)]], {'label': 'Header секция'})}, verbose_name='Header секция'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_slides',
            field=wagtail.fields.StreamField([('slide', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок слайда', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link', 'superscript'], 'label': 'Подзаголовок слайда', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Рекомендуемый размер: 1920x1080px', 'label': 'Изображение', 'required': True}), 3: ('wagtail.blocks.ListBlock', (2,), {'help_text': 'Добавьте до 3 изображений для разных видов: фон, команда, индивидуальное использование', 'label': 'Изображения слайда (до 3)', 'max_num': 3, 'min_num': 1}), 4: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка слайда', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('headline', 0), ('subheadline', 1), ('images', 3), ('link', 4)]], {'label': 'Слайд'})}, verbose_name='Слайды героя'),
        ),
    ]
