# Generated by Django 5.2.7 on 2025-11-01 09:36

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория продукта',
                'verbose_name_plural': 'Категории продуктов',
            },
        ),
        migrations.CreateModel(
            name='ProgramsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Введение')),
            ],
            options={
                'verbose_name': 'Программы',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('buy_link', models.URLField(blank=True)),
                ('content', wagtail.fields.StreamField([('section', 31)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Слева'), ('right', 'Справа')]}), 4: ('wagtail.blocks.CharBlock', (), {'required': True}), 5: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('heading', 4), ('description', 5), ('button_text', 6), ('button_url', 6)]], {}), 8: ('wagtail.blocks.StructBlock', [[('image', 2), ('image_position', 3), ('text_content', 7)]], {}), 9: ('programms.models.ImageCarouselBlock', (), {}), 10: ('programms.models.ImageGridBlock', (), {}), 11: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 12: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic']}), 13: ('wagtail.blocks.ListBlock', (12,), {}), 14: ('wagtail.blocks.StructBlock', [[('items', 13)]], {}), 15: ('wagtail.blocks.RichTextBlock', (), {}), 16: ('wagtail.blocks.StructBlock', [[('text', 15), ('author', 6)]], {}), 17: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 18: ('wagtail.blocks.RawHTMLBlock', (), {}), 19: ('wagtail.blocks.StructBlock', [[('text', 0), ('url', 0)]], {}), 20: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 15)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {}), 22: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 15), ('button_text', 0), ('button_url', 0)]], {}), 23: ('wagtail.blocks.StructBlock', [[]], {}), 24: ('programms.models.CardsBlock', (), {}), 25: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 26: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 27: ('wagtail.blocks.StructBlock', [[('icon', 26), ('value', 0), ('label', 0)]], {}), 28: ('wagtail.blocks.ListBlock', (27,), {}), 29: ('wagtail.blocks.StructBlock', [[('items', 28)]], {}), 30: ('wagtail.blocks.StreamBlock', [[('paragraph', 1), ('image', 8), ('image_carousel', 9), ('image_grid', 10), ('table', 11), ('numbered_list', 14), ('bullet_list', 14), ('quote', 16), ('embed', 17), ('raw_html', 18), ('button', 19), ('accordion', 21), ('tabs', 21), ('call_to_action', 22), ('divider', 23), ('spoiler', 20), ('cards', 24), ('document', 25), ('metrics', 29)]], {'required': False}), 31: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 30)]], {})}, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='programms.productcategory', verbose_name='Категория')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Продукт',
            },
            bases=('wagtailcore.page',),
        ),
    ]
