# Generated by Django 5.2.7 on 2025-10-22 07:47

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Категория',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('buy_link', models.URLField(blank=True, help_text='Ссылка на покупку')),
                ('content', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('image_carousel', 6), ('image_grid', 6), ('table', 7), ('numbered_list', 10), ('bullet_list', 10), ('quote', 12), ('embed', 13), ('raw_html', 14), ('button', 18), ('accordion', 20), ('tabs', 20), ('call_to_action', 22), ('divider', 23), ('spoiler', 19), ('card_list', 26), ('document', 27)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link', 'superscript']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic']}), 9: ('wagtail.blocks.StructBlock', [[('item', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.RichTextBlock', (), {}), 12: ('wagtail.blocks.StructBlock', [[('text', 11), ('author', 4)]], {}), 13: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media'}), 14: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Вставка HTML для кастомного контента, например, видео'}), 15: ('wagtail.blocks.CharBlock', (), {'default': 'Нажмите здесь'}), 16: ('wagtail.blocks.CharBlock', (), {}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'bg-blue-500 text-white', 'help_text': 'Tailwind classes'}), 18: ('wagtail.blocks.StructBlock', [[('text', 15), ('url', 16), ('style', 17)]], {}), 19: ('wagtail.blocks.StructBlock', [[('title', 16), ('content', 11)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {}), 21: ('wagtail.blocks.CharBlock', (), {'default': 'Узнать больше'}), 22: ('wagtail.blocks.StructBlock', [[('title', 16), ('description', 11), ('button_text', 21), ('button_url', 16)]], {}), 23: ('wagtail.blocks.StructBlock', [[]], {}), 24: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 25: ('wagtail.blocks.StructBlock', [[('title', 16), ('image', 24), ('description', 11), ('button_text', 4), ('button_url', 4)]], {}), 26: ('wagtail.blocks.ListBlock', (25,), {}), 27: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'icon': 'doc-full'})}, null=True)),
            ],
            options={
                'verbose_name': 'Продукт',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProgramsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Программы',
            },
            bases=('wagtailcore.page',),
        ),
    ]
