# Generated by Django 5.2.7 on 2025-11-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programspage',
            options={'verbose_name': 'Лента Программ'},
        ),
    ]
