# Generated by Django 5.2.7 on 2025-10-22 08:28

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorypage',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='productpage',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='programspage',
            options={'verbose_name': 'Программы', 'verbose_name_plural': 'Программы'},
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Описание категории программ.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='buy_link',
            field=models.URLField(blank=True, help_text='URL для покупки продукта.', verbose_name='Ссылка на покупку'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='content',
            field=wagtail.fields.StreamField([('hero', 5), ('heading', 6), ('paragraph', 7), ('image', 8), ('image_carousel', 12), ('image_grid', 15), ('table', 16), ('numbered_list', 19), ('bullet_list', 20), ('quote', 23), ('embed', 24), ('raw_html', 25), ('button', 28), ('accordion', 32), ('tabs', 36), ('call_to_action', 40), ('divider', 41), ('spoiler', 44), ('cards', 50), ('document', 51), ('metrics', 57)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Фоновое изображение для hero-секции.', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Заголовок для hero-секции.'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Подзаголовок или описание для hero-секции.'}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Узнать больше', 'help_text': 'Текст кнопки.', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'URL для кнопки.', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('subtitle', 2), ('button_text', 3), ('button_url', 4)]], {'icon': 'image', 'verbose_name': 'Герой'}), 6: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'help_text': 'Основной заголовок секции.', 'icon': 'title', 'verbose_name': 'Заголовок'}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link', 'superscript'], 'help_text': 'Текст с форматированием.', 'verbose_name': 'Параграф'}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Одно изображение для секции.', 'icon': 'image', 'verbose_name': 'Изображение'}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Изображение для карусели.'}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Подпись к изображению.', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('image', 9), ('caption', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'Список изображений для карусели.', 'verbose_name': 'Карусель изображений'}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Изображение для сетки.'}), 14: ('wagtail.blocks.StructBlock', [[('image', 13), ('caption', 10)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {'help_text': 'Сетка изображений с подписями.', 'verbose_name': 'Сетка изображений'}), 16: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'help_text': 'Таблица с данными.', 'verbose_name': 'Таблица'}), 17: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Элемент списка.'}), 18: ('wagtail.blocks.StructBlock', [[('item', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {'help_text': 'Список с номерами.', 'verbose_name': 'Нумерованный список'}), 20: ('wagtail.blocks.ListBlock', (18,), {'help_text': 'Список с маркерами.', 'verbose_name': 'Маркированный список'}), 21: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Текст цитаты.'}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': 'Автор цитаты.', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('text', 21), ('author', 22)]], {'icon': 'openquote', 'verbose_name': 'Цитата'}), 24: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Встраивание видео (YouTube, Vimeo и т.д.).', 'icon': 'media', 'verbose_name': 'Видео'}), 25: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Вставка HTML для кастомного контента.', 'verbose_name': 'HTML-код'}), 26: ('wagtail.blocks.CharBlock', (), {'default': 'Нажмите здесь', 'help_text': 'Текст кнопки.'}), 27: ('wagtail.blocks.CharBlock', (), {'help_text': 'URL для кнопки.'}), 28: ('wagtail.blocks.StructBlock', [[('text', 26), ('url', 27)]], {'icon': 'link', 'verbose_name': 'Кнопка'}), 29: ('wagtail.blocks.CharBlock', (), {'help_text': 'Заголовок аккордеона.'}), 30: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Содержимое аккордеона.'}), 31: ('wagtail.blocks.StructBlock', [[('title', 29), ('content', 30)]], {}), 32: ('wagtail.blocks.ListBlock', (31,), {'help_text': 'Раскрывающиеся секции.', 'verbose_name': 'Аккордеон'}), 33: ('wagtail.blocks.CharBlock', (), {'help_text': 'Заголовок вкладки.'}), 34: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Содержимое вкладки.'}), 35: ('wagtail.blocks.StructBlock', [[('title', 33), ('content', 34)]], {}), 36: ('wagtail.blocks.ListBlock', (35,), {'help_text': 'Переключаемые вкладки.', 'verbose_name': 'Вкладки'}), 37: ('wagtail.blocks.CharBlock', (), {'help_text': 'Заголовок призыва к действию.'}), 38: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Описание призыва к действию.'}), 39: ('wagtail.blocks.CharBlock', (), {'default': 'Узнать больше', 'help_text': 'Текст кнопки.'}), 40: ('wagtail.blocks.StructBlock', [[('title', 37), ('description', 38), ('button_text', 39), ('button_url', 27)]], {'icon': 'pick', 'verbose_name': 'Призыв к действию'}), 41: ('wagtail.blocks.StructBlock', [[]], {'help_text': 'Горизонтальная линия для разделения секций.', 'verbose_name': 'Разделитель'}), 42: ('wagtail.blocks.CharBlock', (), {'help_text': 'Заголовок спойлера.'}), 43: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Содержимое спойлера.'}), 44: ('wagtail.blocks.StructBlock', [[('title', 42), ('content', 43)]], {'icon': 'collapse', 'verbose_name': 'Спойлер'}), 45: ('wagtail.blocks.CharBlock', (), {'help_text': 'Заголовок карточки.'}), 46: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Изображение для карточки.', 'required': False}), 47: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Описание карточки.'}), 48: ('wagtail.blocks.CharBlock', (), {'help_text': 'Текст кнопки.', 'required': False}), 49: ('wagtail.blocks.StructBlock', [[('title', 45), ('image', 46), ('description', 47), ('button_text', 48), ('button_url', 4)]], {}), 50: ('wagtail.blocks.ListBlock', (49,), {'help_text': 'Сетка карточек с заголовком, изображением и описанием.', 'verbose_name': 'Карточки'}), 51: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Ссылка на документ для скачивания.', 'icon': 'doc-full', 'verbose_name': 'Документ'}), 52: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Иконка для метрики.', 'required': False}), 53: ('wagtail.blocks.CharBlock', (), {'help_text': 'Числовое значение метрики.'}), 54: ('wagtail.blocks.CharBlock', (), {'help_text': 'Подпись к метрике.'}), 55: ('wagtail.blocks.StructBlock', [[('icon', 52), ('value', 53), ('label', 54)]], {}), 56: ('wagtail.blocks.ListBlock', (55,), {}), 57: ('wagtail.blocks.StructBlock', [[('items', 56)]], {'icon': 'table', 'verbose_name': 'Метрики'})}, help_text='Гибкое содержимое страницы.', null=True, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Подробное описание продукта.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена продукта в рублях.', max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='programspage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Краткое описание страницы программ.', verbose_name='Введение'),
        ),
    ]
