# Generated by Django 5.2.8 on 2025-12-01 11:42

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('eyebrow', models.CharField(blank=True, max_length=255, verbose_name='Надзаголовок')),
                ('heading', models.CharField(blank=True, max_length=255, verbose_name='Основной заголовок')),
                ('subheading', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('faq_items', wagtail.fields.StreamField([('faq', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Вопрос', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Ответ', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {'icon': 'help', 'label': 'Вопрос-ответ'})}, verbose_name='Вопросы и ответы')),
            ],
            options={
                'verbose_name': 'Страница FAQ',
                'verbose_name_plural': 'Страницы FAQ',
            },
            bases=('wagtailcore.page',),
        ),
    ]
