# Generated by Django 5.2.8 on 2025-12-01 12:39

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('tagline', models.CharField(blank=True, help_text="Краткий слоган решения/продукта, например: 'Система автоматизации контроля ...'", max_length=250, verbose_name='Слоган решения')),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SolutionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('headline', models.CharField(blank=True, max_length=100, verbose_name='Название продукта/решения')),
                ('tagline', models.CharField(blank=True, help_text="Краткий слоган решения/продукта, например: 'Система автоматизации контроля ...'", max_length=250, verbose_name='Слоган решения')),
                ('presentation_file', models.FileField(blank=True, help_text='Презентация в формате PDF или PPTX', null=True, upload_to='presentations/', verbose_name='Презентация')),
                ('intro', wagtail.fields.StreamField([('intro_block', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Рекомендуемый размер: 600x400px', 'label': 'Изображение', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Краткий заголовок карточки', 'label': 'Заголовок', 'max_length': 120}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Описание продукта', 'label': 'Описание', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('description', 2)]], {'label': 'Описание продукта'})}, verbose_name='Блоки описания продукта')),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фоновое изображение для визитки продукта')),
                ('main_image', models.ForeignKey(blank=True, help_text='Рекомендуемый размер 1200x630px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение с примером работы продукта')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
