# Generated by Django 5.2.7 on 2025-11-10 11:06

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, default='', max_length=255)),
                ('content', wagtail.fields.StreamField([('hero', 5), ('values', 11), ('vacancies_list', 13), ('form', 15), ('office', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Карьера в Дио-Консалт'}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'О компании'}), 4: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('background_image', 2), ('cta_text', 3), ('cta_link', 4)]], {'icon': 'image'}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Наши ценности'}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 7), ('description', 1), ('icon', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 6), ('items', 10)]], {'icon': 'list-ul'}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Открытые вакансии'}), 13: ('wagtail.blocks.StructBlock', [[('title', 12)]], {'icon': 'user', 'label': 'Заголовок вакансий'}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'Хотите в команду?'}), 15: ('wagtail.blocks.StructBlock', [[('title', 14), ('description', 1)]], {'icon': 'mail'}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Наш офис'}), 17: ('wagtail.blocks.CharBlock', (), {'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title', 16), ('address', 17)]], {'icon': 'home'})}, default=[])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CareerVacancyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Отдел')),
                ('salary', models.CharField(blank=True, max_length=100, verbose_name='Зарплата')),
                ('location', models.CharField(default='Тюмень', max_length=100, verbose_name='Локация')),
                ('work_format', models.CharField(blank=True, max_length=100, verbose_name='Формат работы')),
                ('description', wagtail.fields.RichTextField(verbose_name='Описание')),
                ('video_url', models.URLField(blank=True, verbose_name='Видео YouTube')),
            ],
            options={
                'verbose_name': 'Вакансия',
            },
            bases=('wagtailcore.page',),
        ),
    ]
