# Generated by Django 5.2.7 on 2025-11-10 11:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careervacancypage',
            name='conditions',
            field=wagtail.fields.StreamField([('condition', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('icon', 0), ('text', 1)]], {})}, verbose_name='Условия'),
        ),
        migrations.AddField(
            model_name='careervacancypage',
            name='gallery',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})}),
        ),
    ]
