# Generated by Django 5.2.7 on 2025-10-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareerPage',
        ),
    ]
