# Generated by Django 5.2.7 on 2025-11-10 11:23

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_careervacancypage_conditions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careervacancypage',
            options={'verbose_name': 'Вакансия (умная)'},
        ),
        migrations.RemoveField(
            model_name='careervacancypage',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='careervacancypage',
            name='department',
        ),
        migrations.RemoveField(
            model_name='careervacancypage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='careervacancypage',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='careervacancypage',
            name='location',
        ),
        migrations.RemoveField(
            model_name='careervacancypage',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='careervacancypage',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='careervacancypage',
            name='work_format',
        ),
        migrations.AddField(
            model_name='careervacancypage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 7), ('duties', 11), ('requirements', 15), ('bonus', 19), ('conditions', 23), ('gallery', 28), ('cta', 31)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': True, 'default': ''}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Продажи'}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'от 120 000 ₽'}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'от 1 года'}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('hot', 'Горячая'), ('new', 'Новинка'), ('remote', 'Удалённо')], 'icon': 'tag', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('department', 2), ('salary', 3), ('experience', 4), ('background', 5), ('badge', 6)]], {'icon': 'title', 'label': 'Герой вакансии'}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Обязанности'}), 9: ('wagtail.blocks.TextBlock', (), {'icon': 'arrow-right'}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 8), ('items', 10)]], {'icon': 'list-ul'}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Требования'}), 13: ('wagtail.blocks.TextBlock', (), {'icon': 'user'}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('title', 12), ('items', 14)]], {'icon': 'warning'}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Будет плюсом'}), 17: ('wagtail.blocks.TextBlock', (), {'icon': 'star'}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.StructBlock', [[('title', 16), ('items', 18)]], {'icon': 'pick'}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('location', 'Локация'), ('schedule', 'График'), ('money', 'Деньги'), ('health', 'ДМС'), ('sport', 'Спорт'), ('food', 'Еда'), ('remote', 'Удалёнка')], 'required': False}), 21: ('wagtail.blocks.TextBlock', (), {}), 22: ('wagtail.blocks.StructBlock', [[('icon', 5), ('icon_svg', 20), ('text', 21)]], {}), 23: ('wagtail.blocks.StreamBlock', [[('condition', 22)]], {'icon': 'cog', 'label': 'Условия'}), 24: ('wagtail.blocks.CharBlock', (), {'default': 'Наш офис — это кайф'}), 25: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 26: ('wagtail.blocks.ListBlock', (25,), {}), 27: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('grid', 'Сетка'), ('masonry', 'Кирпичики'), ('slider', 'Слайдер')]}), 28: ('wagtail.blocks.StructBlock', [[('title', 24), ('images', 26), ('layout', 27)]], {'icon': 'image'}), 29: ('wagtail.blocks.CharBlock', (), {'default': 'Откликнуться за 30 секунд'}), 30: ('wagtail.blocks.CharBlock', (), {'default': 'Хочу в команду!'}), 31: ('wagtail.blocks.StructBlock', [[('text', 29), ('button_text', 30)]], {'icon': 'mail'})}, default=[('hero', {'department': 'Продажи', 'salary': 'от 120 000 ₽'})]),
        ),
        migrations.AlterField(
            model_name='careerpage',
            name='content',
            field=wagtail.fields.StreamField([('hero', 5), ('values', 11), ('vacancies_list', 13), ('form', 15), ('office', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Карьера в Дио-Консалт'}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'О компании'}), 4: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('background_image', 2), ('cta_text', 3), ('cta_link', 4)]], {'icon': 'image'}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Наши ценности'}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 7), ('description', 1), ('icon', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 6), ('items', 10)]], {'icon': 'list-ul'}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Открытые вакансии'}), 13: ('wagtail.blocks.StructBlock', [[('title', 12)]], {'icon': 'user'}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'Хотите в команду?'}), 15: ('wagtail.blocks.StructBlock', [[('title', 14), ('description', 1)]], {'icon': 'mail'}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Наш офис'}), 17: ('wagtail.blocks.CharBlock', (), {'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title', 16), ('address', 17)]], {'icon': 'home'})}, default=[]),
        ),
        migrations.AlterField(
            model_name='careerpage',
            name='intro',
            field=models.CharField(blank=True, default='Присоединяйся к лидерам', max_length=255),
        ),
    ]
