# Generated by Django 5.2.7 on 2025-11-10 11:31

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_alter_careervacancypage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerpage',
            name='content',
        ),
        migrations.AddField(
            model_name='careerpage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 5), ('about', 11), ('values', 16), ('benefits', 19), ('skills', 21), ('form', 23), ('office', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Карьера в Дио-Консалт'}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'О компании'}), 4: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('background_image', 2), ('cta_text', 3), ('cta_link', 4)]], {'icon': 'image'}), 6: ('wagtail.blocks.RichTextBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.StructBlock', [[('number', 7), ('label', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.ListBlock', (7,), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 3), ('description', 6), ('stats', 9), ('services', 10)]], {'icon': 'info'}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Наши ценности'}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 14: ('wagtail.blocks.StructBlock', [[('title', 7), ('description', 6), ('icon', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('title', 12), ('items', 15)]], {'icon': 'heart'}), 17: ('wagtail.blocks.CharBlock', (), {'icon': 'plus'}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.StructBlock', [[('title', 0), ('items', 18)]], {'icon': 'star'}), 20: ('wagtail.blocks.CharBlock', (), {'default': 'Мы ищем специалистов'}), 21: ('wagtail.blocks.StructBlock', [[('title', 20), ('skills', 10)]], {'icon': 'cogs'}), 22: ('wagtail.blocks.CharBlock', (), {'default': 'Хотите в команду?'}), 23: ('wagtail.blocks.StructBlock', [[('title', 22), ('description', 1)]], {'icon': 'mail'}), 24: ('wagtail.blocks.CharBlock', (), {'default': 'Наш офис'}), 25: ('wagtail.blocks.CharBlock', (), {'default': 'Тюмень'}), 26: ('wagtail.blocks.StructBlock', [[('title', 24), ('address', 25)]], {'icon': 'home'})}),
        ),
        migrations.AlterField(
            model_name='careerpage',
            name='intro',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок'),
        ),
    ]
