# Generated by Django 5.2.7 on 2025-11-10 12:04

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_alter_careerpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerpage',
            name='body',
        ),
        migrations.AddField(
            model_name='careerpage',
            name='content',
            field=wagtail.fields.StreamField([('hero', 5), ('values', 11), ('vacancies_list', 13), ('form', 15), ('office', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Карьера в Дио-Консалт'}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'О компании'}), 4: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('background_image', 2), ('cta_text', 3), ('cta_link', 4)]], {'icon': 'image'}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Наши ценности'}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 7), ('description', 1), ('icon', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 6), ('items', 10)]], {'icon': 'list-ul'}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Открытые вакансии'}), 13: ('wagtail.blocks.StructBlock', [[('title', 12)]], {'icon': 'user'}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'Хотите в команду?'}), 15: ('wagtail.blocks.StructBlock', [[('title', 14), ('description', 1)]], {'icon': 'mail'}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Наш офис'}), 17: ('wagtail.blocks.CharBlock', (), {'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title', 16), ('address', 17)]], {'icon': 'home'})}, default=[]),
        ),
        migrations.AlterField(
            model_name='careerpage',
            name='intro',
            field=models.CharField(blank=True, default='Присоединяйся к лидерам', max_length=255),
        ),
    ]
