# Generated by Django 5.2.7 on 2025-11-10 12:07

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0006_remove_careerpage_body_careerpage_content_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careervacancypage',
            options={'verbose_name': 'Вакансия'},
        ),
        migrations.AddField(
            model_name='careervacancypage',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='careervacancypage',
            name='badge',
            field=models.CharField(blank=True, choices=[('hot', 'Горячая'), ('new', 'Новинка'), ('remote', 'Удалённо'), ('urgent', 'Срочно')], help_text='Метка на карточке', max_length=20),
        ),
        migrations.AddField(
            model_name='careervacancypage',
            name='department',
            field=models.CharField(default='Продажи', max_length=100),
        ),
        migrations.AddField(
            model_name='careervacancypage',
            name='experience',
            field=models.CharField(blank=True, help_text='Например: от 1 года', max_length=100),
        ),
        migrations.AddField(
            model_name='careervacancypage',
            name='salary',
            field=models.CharField(default='от 120 000 ₽', max_length=100),
        ),
        migrations.AlterField(
            model_name='careervacancypage',
            name='body',
            field=wagtail.fields.StreamField([('duties', 3), ('requirements', 7), ('bonus', 11), ('conditions', 15), ('gallery', 20), ('video', 21), ('cta', 24)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Обязанности'}), 1: ('wagtail.blocks.TextBlock', (), {'icon': 'arrow-right'}), 2: ('wagtail.blocks.ListBlock', (1,), {}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('items', 2)]], {'icon': 'list-ul', 'label': 'Обязанности'}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Требования'}), 5: ('wagtail.blocks.TextBlock', (), {'icon': 'user'}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('title', 4), ('items', 6)]], {'icon': 'warning', 'label': 'Требования'}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Будет плюсом'}), 9: ('wagtail.blocks.TextBlock', (), {'icon': 'star'}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 8), ('items', 10)]], {'icon': 'pick', 'label': 'Плюсом'}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('briefcase', 'Офис'), ('clock', 'График'), ('rub', 'Зарплата'), ('heart', 'ДМС'), ('dumbbell', 'Спорт'), ('pizza', 'Еда'), ('home', 'Удалённо'), ('gift', 'Бонусы')], 'icon': 'cog'}), 13: ('wagtail.blocks.TextBlock', (), {}), 14: ('wagtail.blocks.StructBlock', [[('icon', 12), ('text', 13)]], {'icon': 'cog'}), 15: ('wagtail.blocks.ListBlock', (14,), {'label': 'Условие'}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Наш офис — это кайф'}), 17: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('grid', 'Сетка'), ('masonry', 'Кирпичики'), ('carousel', 'Карусель')]}), 20: ('wagtail.blocks.StructBlock', [[('title', 16), ('images', 18), ('layout', 19)]], {'icon': 'image', 'label': 'Галерея'}), 21: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube или Vimeo'}), 22: ('wagtail.blocks.CharBlock', (), {'default': 'Готов стать частью команды?'}), 23: ('wagtail.blocks.CharBlock', (), {'default': 'Откликнуться за 30 секунд'}), 24: ('wagtail.blocks.StructBlock', [[('text', 22), ('button_text', 23)]], {'icon': 'mail', 'label': 'Призыв к действию'})}),
        ),
    ]
