# Generated by Django 5.2.7 on 2025-10-14 10:25

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0006_alter_careerpage_content'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerpage',
            name='content',
        ),
        migrations.AddField(
            model_name='careerpage',
            name='advantages_list',
            field=models.TextField(blank=True, default='Гибкий график работы\nВозможность удалёнки\nКонкурентные зарплаты\nПрофессиональный рост\nКорпоративное обучение', help_text='Список преимуществ (каждый пункт с новой строки)'),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='career_title',
            field=models.CharField(blank=True, default='Карьера в ALMA', help_text="Заголовок секции 'Карьера в ALMA'", max_length=255),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='directions_list',
            field=models.TextField(blank=True, default='Проектное управление | Координация и контроль проектов\nФинансовый анализ | Анализ и планирование финансов\nРазработка ПО | Создание и поддержка программных решений', help_text="Список направлений (каждый пункт: 'Название | Описание' с новой строки)"),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='directions_title',
            field=models.CharField(blank=True, default='Направления', help_text="Заголовок секции 'Направления/Вакансии'", max_length=255),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='form_description',
            field=wagtail.fields.RichTextField(blank=True, default='Расскажите о своем опыте и кем вы видите себя в ALMA. Оставьте контакты и прикрепите резюме - мы обязательно свяжемся с вами в случае подходящей вакансии.', help_text='Описание формы отклика'),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='form_privacy_link',
            field=models.CharField(blank=True, default='/privacy-policy/', help_text='Ссылка на политику конфиденциальности', max_length=255),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='form_privacy_text',
            field=models.CharField(blank=True, default='Нажимая кнопку, я принимаю соглашение о конфиденциальности и соглашаюсь с обработкой персональных данных', help_text='Текст согласия с политикой конфиденциальности', max_length=255),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='form_recaptcha_note',
            field=models.TextField(blank=True, default='This site is protected by reCAPTCHA and the Google Privacy Policy and Terms of Service apply.', help_text='Примечание о reCAPTCHA'),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='form_title',
            field=models.CharField(blank=True, default='Хотите в команду?', help_text='Заголовок секции формы', max_length=255),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='hero_about_link',
            field=models.CharField(blank=True, default='/about/', help_text="Ссылка на страницу 'О компании'", max_length=255),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='hero_about_link_text',
            field=models.CharField(blank=True, default='Подробнее', help_text="Текст ссылки на страницу 'О компании'", max_length=50),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='hero_additional_descriptions',
            field=models.TextField(blank=True, default='Разрабатываем собственные программные решения для отраслей\nВнедряем ИИ и ML в процессы управления производством, предиктивного анализа, автоматизации', help_text='Дополнительные описания (каждый абзац с новой строки)'),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='hero_description',
            field=wagtail.fields.RichTextField(blank=True, default='ALMA — команда профессионалов, работающая с крупнейшими нефтегазовыми компаниями в России и за её пределами', help_text='Основное описание в секции Hero'),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='hero_service_list',
            field=models.TextField(blank=True, default='IT-компании и ИТ-подразделения\nПромышленные и технологические предприятия\nОрганизаций, стремящихся повысить эффективность управления', help_text='Список сервисов и услуг (каждый пункт с новой строки)'),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='hero_title',
            field=models.CharField(blank=True, default='Карьера', help_text='Заголовок секции Hero', max_length=255),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='metric_projects_label',
            field=models.CharField(blank=True, default='Реализованных проектов', help_text='Заголовок метрики проектов', max_length=50),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='metric_projects_value',
            field=models.CharField(blank=True, default='35+', help_text='Значение метрики проектов', max_length=50),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='metric_year_label',
            field=models.CharField(blank=True, default='Год основания компании', help_text='Заголовок метрики года', max_length=50),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='metric_year_value',
            field=models.CharField(blank=True, default='2017', help_text='Значение метрики года', max_length=50),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='office_address',
            field=models.CharField(blank=True, default='Москва, ул. Примерная, д. 1', help_text='Адрес офиса', max_length=255),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='office_image',
            field=models.ForeignKey(blank=True, help_text='Изображение офиса (опционально)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='office_title',
            field=models.CharField(blank=True, default='Наш офис', help_text="Заголовок секции 'Наш офис'", max_length=255),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='values_list',
            field=models.TextField(blank=True, default='Вовлечённость и работа на результат | Мы всегда ориентированы на достижение целей и вовлечены в процесс\nИнновации и развитие | Постоянно внедряем новые технологии для роста\nКомандная работа | Поддерживаем друг друга и делимся знаниями', help_text="Список ценностей (каждый пункт: 'Заголовок | Описание' с новой строки)"),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='values_title',
            field=models.CharField(blank=True, default='Наши ценности', help_text="Заголовок секции 'Наши ценности'", max_length=255),
        ),
    ]
