# Generated by Django 5.2.7 on 2025-11-14 09:13

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0007_alter_careervacancypage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerpage',
            options={'verbose_name': "Страница 'Карьера'", 'verbose_name_plural': "Страницы 'Карьера'"},
        ),
        migrations.AlterModelOptions(
            name='careervacancypage',
            options={'verbose_name': "Страница 'Вакансия'", 'verbose_name_plural': "Страницы 'Вакансии'"},
        ),
        migrations.RemoveField(
            model_name='careerpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='careervacancypage',
            name='background',
        ),
        migrations.RemoveField(
            model_name='careervacancypage',
            name='experience',
        ),
        migrations.AddField(
            model_name='careervacancypage',
            name='location',
            field=models.CharField(default='Сыктывкар', max_length=100),
        ),
        migrations.AddField(
            model_name='careervacancypage',
            name='work_format',
            field=models.CharField(choices=[('office', 'Офис'), ('remote', 'Удалённо'), ('hybrid', 'Гибрид')], default='office', max_length=50),
        ),
        migrations.AlterField(
            model_name='careerpage',
            name='content',
            field=wagtail.fields.StreamField([('hero', 5), ('text_section', 8), ('values', 13), ('vacancies_list', 15), ('form', 17), ('office', 20)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Присоединяйся к DIO'}), 1: ('wagtail.blocks.TextBlock', (), {'blank': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'blank': True}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Смотреть вакансии'}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Прокрутка к вакансиям'}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('image', 2), ('cta_text', 3), ('cta_scroll', 4)]], {'icon': 'image'}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'О компании'}), 7: ('wagtail.blocks.RichTextBlock', (), {'blank': True}), 8: ('wagtail.blocks.StructBlock', [[('title', 6), ('content', 7), ('image', 2)]], {'icon': 'doc-full'}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Наши ценности'}), 10: ('wagtail.blocks.CharBlock', (), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 10), ('description', 1), ('icon', 2)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('title', 9), ('items', 12)]], {'icon': 'list-ul'}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'Открытые вакансии'}), 15: ('wagtail.blocks.StructBlock', [[('title', 14)]], {'icon': 'user'}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Хочешь к нам?'}), 17: ('wagtail.blocks.StructBlock', [[('title', 16), ('description', 1)]], {'icon': 'mail'}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Наш офис'}), 19: ('wagtail.blocks.CharBlock', (), {'blank': True}), 20: ('wagtail.blocks.StructBlock', [[('title', 18), ('address', 19)]], {'icon': 'home'})}),
        ),
        migrations.AlterField(
            model_name='careervacancypage',
            name='badge',
            field=models.CharField(blank=True, choices=[('hot', 'Горячая'), ('new', 'Новая'), ('remote', 'Удалённо')], max_length=20),
        ),
        migrations.AlterField(
            model_name='careervacancypage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('list', 3), ('image', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.blocks.CharBlock', (), {'icon': 'list-ul'}), 3: ('wagtail.blocks.ListBlock', (2,), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'})}),
        ),
        migrations.AlterField(
            model_name='careervacancypage',
            name='department',
            field=models.CharField(default='Разработка', max_length=100),
        ),
        migrations.AlterField(
            model_name='careervacancypage',
            name='salary',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
