# Generated by Django 5.2.7 on 2025-11-14 09:26

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0008_alter_careerpage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careervacancypage',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AddField(
            model_name='careervacancypage',
            name='experience',
            field=models.CharField(blank=True, help_text='Например: от 1 года', max_length=100),
        ),
        migrations.AlterField(
            model_name='careervacancypage',
            name='badge',
            field=models.CharField(blank=True, choices=[('hot', 'Горячая'), ('new', 'Новая'), ('remote', 'Удалённо'), ('urgent', 'Срочно')], help_text='Метка на карточке', max_length=20),
        ),
        migrations.AlterField(
            model_name='careervacancypage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('list_block', 5), ('conditions', 11), ('gallery', 16), ('video', 17), ('cta', 21)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h3', 'h4'], 'icon': 'pilcrow'}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Обязанности'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Пункт'}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 2), ('items', 4)]], {'icon': 'list-ul'}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Условия'}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('briefcase', 'Офис'), ('clock', 'График'), ('rub', 'Зарплата'), ('heart', 'ДМС'), ('dumbbell', 'Спорт'), ('pizza', 'Еда'), ('home', 'Удалённо'), ('gift', 'Бонусы')], 'icon': 'cog'}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('icon', 7), ('text', 8)]], {'icon': 'cog'}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 6), ('items', 10)]], {'icon': 'cog'}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Наш офис'}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('grid', 'Сетка'), ('masonry', 'Кирпичики')]}), 16: ('wagtail.blocks.StructBlock', [[('title', 12), ('images', 14), ('layout', 15)]], {'icon': 'image'}), 17: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube или Vimeo', 'icon': 'media'}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Готов стать частью команды?'}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'Откликнуться'}), 20: ('wagtail.blocks.CharBlock', (), {'default': '#vacancy-form'}), 21: ('wagtail.blocks.StructBlock', [[('text', 18), ('button_text', 19), ('button_link', 20)]], {'icon': 'mail'})}),
        ),
        migrations.AlterField(
            model_name='careervacancypage',
            name='salary',
            field=models.CharField(blank=True, help_text='Например: от 150 000 ₽', max_length=100),
        ),
    ]
