# Generated by Django 5.2.7 on 2025-11-14 09:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0009_alter_careervacancypage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careervacancypage',
            name='body',
            field=wagtail.fields.StreamField([('duties', 2), ('requirements', 5), ('benefits', 10), ('description', 11), ('office_gallery', 15), ('team_video', 16), ('cta', 19)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Обязанность'}), 1: ('wagtail.blocks.ListBlock', (0,), {}), 2: ('wagtail.blocks.StructBlock', [[('items', 1)]], {'icon': 'list-ul', 'label': 'Обязанности'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Требование'}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('items', 4)]], {'icon': 'check', 'label': 'Требования'}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('rub', 'Зарплата'), ('clock', 'График'), ('home', 'Удалённо'), ('heart', 'ДМС'), ('dumbbell', 'Спорт'), ('pizza', 'Питание'), ('gift', 'Бонусы'), ('briefcase', 'Офис')], 'icon': 'cog'}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Описание'}), 8: ('wagtail.blocks.StructBlock', [[('icon', 6), ('text', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('items', 9)]], {'icon': 'star', 'label': 'Условия'}), 11: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h3', 'h4'], 'icon': 'pilcrow', 'label': 'Описание'}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Наш офис'}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('title', 12), ('images', 14)]], {'icon': 'image', 'label': 'Галерея'}), 16: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube или Vimeo', 'icon': 'media', 'label': 'Видео о команде'}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'Готов стать частью DIO?'}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Откликнуться'}), 19: ('wagtail.blocks.StructBlock', [[('text', 17), ('button_text', 18)]], {'icon': 'mail', 'label': 'Призыв к действию'})}, default=[]),
        ),
    ]
