# Generated by Django 5.2.7 on 2025-11-14 09:53

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0010_alter_careervacancypage_body'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careervacancypage',
            name='experience',
        ),
        migrations.AddField(
            model_name='careervacancypage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Фон для Hero', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='careervacancypage',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text='Мотивация за 1 строку', max_length=300),
        ),
        migrations.AddField(
            model_name='careervacancypage',
            name='hero_title',
            field=models.CharField(default='Стань частью DIO', max_length=200),
        ),
        migrations.AddField(
            model_name='careervacancypage',
            name='vibe',
            field=models.CharField(choices=[('creative', 'Креатив'), ('tech', 'Технологии'), ('growth', 'Рост'), ('freedom', 'Свобода')], default='tech', help_text='Общая атмосфера', max_length=50),
        ),
        migrations.AlterField(
            model_name='careervacancypage',
            name='badge',
            field=models.CharField(blank=True, choices=[('hot', 'Горячая'), ('new', 'Новая'), ('remote', 'Удалённо'), ('urgent', 'Срочно')], max_length=20),
        ),
        migrations.AlterField(
            model_name='careervacancypage',
            name='body',
            field=wagtail.fields.StreamField([('duties', 1), ('requirements', 3), ('benefits', 7), ('gallery', 10), ('video', 11), ('cta', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Что ты будешь делать'}), 1: ('wagtail.blocks.ListBlock', (0,), {'icon': 'list-ul'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Что мы ищем'}), 3: ('wagtail.blocks.ListBlock', (2,), {'icon': 'check'}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('rocket', 'Рост'), ('target', 'Цели'), ('users', 'Команда'), ('zap', 'Скорость'), ('heart', 'Забота'), ('trophy', 'Победа')]}), 5: ('wagtail.blocks.CharBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('icon', 4), ('text', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'icon': 'star'}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('images', 9)]], {'icon': 'image'}), 11: ('wagtail.blocks.URLBlock', (), {'icon': 'media'}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Готов изменить будущее?'}), 13: ('wagtail.blocks.CharBlock', (), {'default': 'Присоединиться'}), 14: ('wagtail.blocks.StructBlock', [[('text', 12), ('button', 13)]], {'icon': 'mail'})}),
        ),
        migrations.AlterField(
            model_name='careervacancypage',
            name='salary',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
