# Generated by Django 5.2.7 on 2025-11-14 10:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0011_remove_careervacancypage_experience_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careervacancypage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='careervacancypage',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='careervacancypage',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='careervacancypage',
            name='vibe',
        ),
        migrations.AddField(
            model_name='careervacancypage',
            name='content',
            field=wagtail.fields.StreamField([('section', 23)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Заголовок секции'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h3', 'h4'], 'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Слева'), ('right', 'Справа')]}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.RichTextBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'blank': True}), 7: ('wagtail.blocks.URLBlock', (), {'blank': True}), 8: ('wagtail.blocks.StructBlock', [[('heading', 4), ('description', 5), ('button_text', 6), ('button_url', 7)]], {}), 9: ('wagtail.blocks.StructBlock', [[('image', 2), ('image_position', 3), ('text_content', 8)]], {'icon': 'image'}), 10: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 6)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'icon': 'image'}), 12: ('wagtail.blocks.ListBlock', (5,), {'icon': 'list-ol'}), 13: ('wagtail.blocks.ListBlock', (5,), {'icon': 'list-ul'}), 14: ('wagtail.blocks.StructBlock', [[('text', 5), ('author', 6)]], {'icon': 'openquote'}), 15: ('wagtail.blocks.StructBlock', [[('title', 4), ('content', 5)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'icon': 'pilcrow'}), 17: ('wagtail.blocks.URLBlock', (), {}), 18: ('wagtail.blocks.StructBlock', [[('title', 4), ('description', 5), ('button_text', 4), ('button_url', 17)]], {'icon': 'mail'}), 19: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 20: ('wagtail.blocks.StructBlock', [[('image', 19), ('title', 4), ('description', 5), ('button_text', 6), ('button_url', 7)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'icon': 'grip'}), 22: ('wagtail.blocks.StreamBlock', [[('paragraph', 1), ('image', 9), ('image_carousel', 11), ('image_grid', 11), ('numbered_list', 12), ('bullet_list', 13), ('quote', 14), ('accordion', 16), ('call_to_action', 18), ('cards', 21)]], {'use_json_field': True}), 23: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 22)]], {'icon': 'folder-open'})}),
        ),
        migrations.AlterField(
            model_name='careervacancypage',
            name='badge',
            field=models.CharField(blank=True, choices=[('hot', 'Горячая'), ('new', 'Новая'), ('remote', 'Удалённо'), ('urgent', 'Срочно')], help_text='Метка на карточке', max_length=20),
        ),
        migrations.AlterField(
            model_name='careervacancypage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='careervacancypage',
            name='salary',
            field=models.CharField(blank=True, help_text='Например: от 150 000 ₽', max_length=100),
        ),
    ]
