# Generated by Django 5.2.7 on 2025-11-14 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0012_remove_careervacancypage_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careervacancypage',
            name='badge',
        ),
    ]
