# Generated by Django 5.2.7 on 2025-11-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0015_alter_careerpage_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careervacancypage',
            name='location',
            field=models.CharField(default='Тюмень', max_length=100),
        ),
    ]
