# Generated by Django 5.2.6 on 2025-09-30 09:12

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_content', models.TextField(help_text='Основной текстовый контент документа', verbose_name='Содержимое документа')),
                ('metadata', wagtail.fields.StreamField([('key_value_pairs', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Введите название ключа', 'label': 'Ключ', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Введите значение', 'label': 'Значение', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('key', 0), ('value', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {'help_text': 'Добавляйте произвольное количество пар ключ-значение', 'label': 'Поля ключ-значение'})}, default=[])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Добавленые документы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/%d/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Загруженные документы',
                'ordering': ['-created_at'],
            },
        ),
    ]
