# Generated by Django 5.2.6 on 2025-09-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='AddDocument',
        ),
    ]
