# Generated by Django 5.2.6 on 2025-09-30 09:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddocument',
            name='metadata',
            field=wagtail.fields.StreamField([('metadata', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Ключ', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Значение', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('key', 0), ('value', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {'help_text': 'Добавляйте любое количество полей ключ-значение', 'label': 'Поля метаданных'}), 4: ('wagtail.blocks.StructBlock', [[('metadata_fields', 3)]], {})}, verbose_name='Metadata'),
        ),
    ]
