# Generated by Django 5.2.6 on 2025-09-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_rename_document_adddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddocument',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные метаданные в формате JSON', verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='adddocument',
            name='page_content',
            field=models.TextField(help_text='Основной текстовый контент документа', verbose_name='Содержимое документа'),
        ),
    ]
