# Generated by Django 5.2.6 on 2025-09-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_adddocument_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/%d/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Загруженные документы',
                'ordering': ['-created_at'],
            },
        ),
    ]
