# Generated by Django 5.2.6 on 2025-09-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_adddocument_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocument',
            name='file',
            field=models.FileField(default='', upload_to='resumes/%Y/%m/%d/', verbose_name='Файл'),
            preserve_default=False,
        ),
    ]
