# Generated by Django 5.2.6 on 2025-09-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_alter_uploaddocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocument',
            name='file',
            field=models.FileField(upload_to='upload/%Y/%m/%d/', verbose_name='Файл'),
        ),
    ]
