# Generated by Django 5.2.6 on 2025-09-30 11:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_alter_adddocument_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddocument',
            name='metadata',
            field=wagtail.fields.StreamField([('metadata', 0)], blank=True, block_lookup={0: ('ai.blocks.MetadataBlock', (), {})}),
        ),
    ]
