# Generated by Django 5.2.6 on 2025-09-30 11:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_alter_adddocument_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adddocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Добавленные документы'},
        ),
        migrations.AlterField(
            model_name='adddocument',
            name='metadata',
            field=wagtail.fields.StreamField([('metadata', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Содержание', 'max_length': 500, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('key', 0), ('value', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {'help_text': 'Добавляйте элементы метаданных', 'label': 'Метаданные'})}, verbose_name='Метаданные документа'),
        ),
    ]
