# Generated by Django 5.2.6 on 2025-10-01 07:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_alter_adddocument_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddocument',
            name='metadata',
            field=wagtail.fields.StreamField([('metadata', 0)], blank=True, block_lookup={0: ('ai.blocks.MetadataBlock', (), {'max_num': 1})}, verbose_name='Метаданные документа'),
        ),
    ]
