# Generated by Django 5.2.8 on 2025-11-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0011_alter_adddocument_metadata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddDocument',
        ),
    ]
