# Generated by Django 5.2.7 on 2025-11-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_email', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminemail',
            name='name',
        ),
        migrations.AddField(
            model_name='adminemail',
            name='fio',
            field=models.CharField(blank=True, verbose_name='ФИО администратора'),
        ),
    ]
