# Generated by Django 5.2.6 on 2025-09-13 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('icon', models.CharField(blank=True, help_text='Название иконки (например: cog, chart-line, users)', max_length=50, verbose_name='Иконка услуги')),
                ('category', models.CharField(choices=[('consulting', 'Консалтинг и автоматизация'), ('development', 'Разработка'), ('support', 'Сопровождение 1С'), ('education', 'Обучение 1С')], default='consulting', max_length=100, verbose_name='Категория услуг')),
                ('short_description', models.CharField(blank=True, help_text='Короткое описание для карточек и списков', max_length=250, verbose_name='Краткое описание')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
