# Generated by Django 5.2.6 on 2025-09-13 13:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='short_description',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото-карточка услуги'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Краткое описание услуги'),
        ),
    ]
