# Generated by Django 5.2.6 on 2025-09-25 04:44

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_servicepage_icon_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('industry', models.CharField(blank=True, choices=[('neftegaz', 'Нефтегаз'), ('stroitelstvo', 'Строительство'), ('energetika', 'Энергетика')], max_length=100)),
                ('hero_title', models.CharField(blank=True, help_text='Заголовок hero', max_length=255)),
                ('hero_subtitle', models.CharField(blank=True, help_text='Подзаголовок hero', max_length=255)),
                ('description', wagtail.fields.StreamField([('description_block', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок описания', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Что мы делаем'}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': "Список 'Что мы делаем'"}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 1), ('what_we_do', 3)]], {})}, verbose_name='Описание услуги')),
                ('industries_expertise', wagtail.fields.StreamField([('industry_expertise', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название отрасли', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка отрасли', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('icon', 1)]], {})}, verbose_name='Отраслевая экспертиза')),
                ('cta_title', models.CharField(blank=True, help_text='Заголовок CTA', max_length=255)),
                ('cta_description', wagtail.fields.RichTextField(blank=True, help_text='Описание CTA')),
            ],
            options={
                'verbose_name': 'Отдельная услуга',
                'verbose_name_plural': 'Отдельные услуги',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_title', models.CharField(blank=True, help_text='Заголовок секции услуг', max_length=255)),
                ('intro_description', wagtail.fields.RichTextField(blank=True, help_text='Описание секции услуг')),
                ('services', wagtail.fields.StreamField([('service_item', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название услуги', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание услуги', 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка (SVG или изображение)', 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка на страницу услуги', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('icon', 2), ('link', 3)]], {})}, verbose_name='Элементы услуг')),
                ('industries', wagtail.fields.StreamField([('industry', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название отрасли', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка отрасли', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('icon', 1)]], {})}, verbose_name='Отраслевая экспертиза')),
                ('cta_text', models.CharField(blank=True, help_text='Текст кнопки CTA', max_length=255)),
                ('cta_link', models.ForeignKey(blank=True, help_text='Ссылка для CTA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Страница услуг',
                'verbose_name_plural': 'Страницы услуг',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='ServicePage',
        ),
    ]
