# Generated by Django 5.2.6 on 2025-09-25 05:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_singleservicepage_servicespage_delete_servicepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleservicepage',
            name='cta_description',
        ),
        migrations.RemoveField(
            model_name='singleservicepage',
            name='cta_title',
        ),
        migrations.RemoveField(
            model_name='singleservicepage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='singleservicepage',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='singleservicepage',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='singleservicepage',
            name='industries_expertise',
        ),
        migrations.RemoveField(
            model_name='singleservicepage',
            name='industry',
        ),
        migrations.AddField(
            model_name='singleservicepage',
            name='content',
            field=wagtail.fields.StreamField([('hero', 2), ('what_we_do', 6), ('industry_expertise', 9), ('services', 12), ('cta', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок Hero', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Подзаголовок Hero', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции', 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Элемент списка'}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Список действий'}), 6: ('wagtail.blocks.StructBlock', [[('title', 3), ('items', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Отрасль'}), 8: ('wagtail.blocks.ListBlock', (7,), {'label': 'Список отраслей'}), 9: ('wagtail.blocks.StructBlock', [[('title', 3), ('industries', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Услуга'}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Список услуг'}), 12: ('wagtail.blocks.StructBlock', [[('title', 3), ('items', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок CTA', 'required': True}), 14: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание CTA', 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'label': 'Текст ссылки', 'required': True}), 16: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка на страницу', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title', 13), ('description', 14), ('link_text', 15), ('link_page', 16)]], {})}, verbose_name='Секции страницы'),
        ),
        migrations.DeleteModel(
            name='ServicesPage',
        ),
    ]
