# Generated by Django 5.2.6 on 2025-09-25 05:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_singleservicepage_cta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleservicepage',
            name='content',
            field=wagtail.fields.StreamField([('hero', 3), ('what_we_do', 7), ('image_block', 9), ('industry_expertise', 12), ('services', 15), ('cta', 20)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок Hero', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Подзаголовок Hero', 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('image', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции', 'required': True}), 5: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание', 'required': True}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'SVG изображение', 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('title', 4), ('description', 5), ('svg_image', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Альтернативный текст', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 2), ('alt_text', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Отрасль'}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Список отраслей'}), 12: ('wagtail.blocks.StructBlock', [[('title', 4), ('industries', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Услуга'}), 14: ('wagtail.blocks.ListBlock', (13,), {'label': 'Список услуг'}), 15: ('wagtail.blocks.StructBlock', [[('title', 4), ('items', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок CTA', 'required': True}), 17: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание CTA', 'required': True}), 18: ('wagtail.blocks.CharBlock', (), {'label': 'Текст ссылки', 'required': True}), 19: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка на страницу', 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('title', 16), ('description', 17), ('link_text', 18), ('link_page', 19)]], {})}, verbose_name='Секции страницы'),
        ),
    ]
