# Generated by Django 5.2.6 on 2025-09-25 06:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_singleservicepage_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singleservicepage',
            options={'verbose_name': 'Страница услуги', 'verbose_name_plural': 'Страницы услуг'},
        ),
        migrations.AlterField(
            model_name='singleservicepage',
            name='content',
            field=wagtail.fields.StreamField([('hero', 3), ('what_we_do', 7), ('square_image', 10), ('expertise_grid', 14), ('cta', 19)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок Hero', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Подзаголовок Hero', 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение Hero', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('image', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 5: ('wagtail.blocks.RichTextBlock', (), {'label': 'Большой текст справа', 'required': True}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'SVG/изображение слева', 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('title', 4), ('description', 5), ('svg_image', 6)]], {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Квадратное изображение', 'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Альтернативный текст', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 8), ('alt_text', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок сетки', 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Элемент сетки'}), 13: ('wagtail.blocks.ListBlock', (12,), {'label': 'Список отраслей/услуг'}), 14: ('wagtail.blocks.StructBlock', [[('title', 11), ('items', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок CTA', 'required': True}), 16: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание CTA', 'required': True}), 17: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'required': True}), 18: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка', 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('title', 15), ('description', 16), ('link_text', 17), ('link_page', 18)]], {})}, verbose_name='Блоки страницы'),
        ),
    ]
