# Generated by Django 5.2.6 on 2025-09-25 06:54

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_singleservicepage_options_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('hero', 3), ('service_list', 10), ('cta', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок Hero', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Подзаголовок Hero', 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение Hero', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('image', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок списка', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Название услуги'}), 6: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание'}), 7: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка на страницу', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 5), ('description', 6), ('link_page', 7)]], {'label': 'Услуга'}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('title', 4), ('services', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок CTA', 'required': True}), 12: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание CTA', 'required': True}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'required': True}), 14: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('title', 11), ('description', 12), ('link_text', 13), ('link_page', 14)]], {})}, verbose_name='Секции страницы')),
            ],
            options={
                'verbose_name': 'Страница услуг',
                'verbose_name_plural': 'Страницы услуг',
            },
            bases=('wagtailcore.page',),
        ),
    ]
