# Generated by Django 5.2.6 on 2025-09-25 07:09

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicepage'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Введение')),
                ('items_per_page', models.PositiveIntegerField(default=9, verbose_name='Услуг на странице')),
            ],
            options={
                'verbose_name': 'Лента услуг',
                'verbose_name_plural': 'Ленты услуг',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='singleservicepage',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='singleservicepage',
            name='category',
            field=models.CharField(choices=[('consulting', 'Консультации'), ('development', 'Разработка'), ('design', 'Дизайн'), ('support', 'Поддержка'), ('training', 'Обучение')], default='consulting', max_length=100, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='singleservicepage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='singleservicepage',
            name='headline',
            field=models.CharField(default='Заголовок услуги', max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='singleservicepage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='singleservicepage',
            name='intro',
            field=models.TextField(blank=True, help_text='1-3 предложения для анонса', verbose_name='Краткое описание'),
        ),
        migrations.DeleteModel(
            name='ServicePage',
        ),
    ]
