# Generated by Django 5.2.7 on 2025-10-09 08:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_serviceindexpage_alter_singleservicepage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleservicepage',
            name='content',
            field=wagtail.fields.StreamField([('hero', 3), ('flexible_content', 18), ('cta', 23)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок Hero', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Подзаголовок Hero', 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение Hero', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('image', 2)]], {}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('what_we_do', 'Что мы делаем'), ('expertise_grid', 'Сетка отраслей/услуг'), ('square_image', 'Квадратное изображение')], 'label': 'Тип блока'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 6: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание справа', 'required': True}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение слева', 'required': True}), 8: ('wagtail.blocks.StructBlock', [[('title', 5), ('description', 6), ('image', 7)]], {'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок сетки', 'required': True}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Название элемента', 'required': True}), 11: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание элемента', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 10), ('description', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'label': 'Список отраслей/услуг'}), 14: ('wagtail.blocks.StructBlock', [[('title', 9), ('items', 13)]], {'required': False}), 15: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Квадратное изображение', 'required': True}), 16: ('wagtail.blocks.CharBlock', (), {'label': 'Альтернативный текст', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('image', 15), ('alt_text', 16)]], {'required': False}), 18: ('wagtail.blocks.StructBlock', [[('block_type', 4), ('what_we_do', 8), ('expertise_grid', 14), ('square_image', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок CTA', 'required': True}), 20: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание CTA', 'required': True}), 21: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'required': True}), 22: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('title', 19), ('description', 20), ('link_text', 21), ('link_page', 22)]], {})}, verbose_name='Блоки страницы'),
        ),
    ]
