# Generated by Django 5.2.7 on 2025-11-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_singleservicepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleservicepage',
            name='category',
            field=models.CharField(choices=[('consulting', 'Консультации'), ('development', 'Разработка'), ('design', 'Дизайн'), ('support', 'Поддержка'), ('training', 'Обучение'), ('1_c', '1С')], default='consulting', max_length=100, verbose_name='Категория'),
        ),
    ]
