# Generated by Django 5.2.8 on 2025-12-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_servicepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicePage',
        ),
    ]
