# Generated by Django 5.2.8 on 2025-12-01 11:42

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Введение')),
                ('items_per_page', models.PositiveIntegerField(default=9, verbose_name='Новостей на странице')),
            ],
            options={
                'verbose_name': 'Лента новостей',
                'verbose_name_plural': 'Ленты новостей',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('read_time', models.PositiveIntegerField(default=1, help_text='Примерное время чтения статьи в минутах', verbose_name='Время чтения (мин)')),
                ('category', models.CharField(choices=[('company', 'Новости компании'), ('tech', 'Технологии'), ('projects', 'Проекты'), ('events', 'События'), ('awards', 'Награды')], default='company', max_length=100, verbose_name='Категория')),
                ('headline', models.CharField(default='Заголовок новости', max_length=255, verbose_name='Заголовок')),
                ('intro', models.TextField(blank=True, help_text='1-3 предложения для анонса', verbose_name='Краткое описание')),
                ('media_content', wagtail.fields.StreamField([('image', 2), ('video', 4), ('embed', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {'label': 'Изображение'}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Ссылка на YouTube, Vimeo и т.д.', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('video_url', 3), ('caption', 1)]], {'label': 'Видео'}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Вставьте ссылку на видео (YouTube, Vimeo и т.д.)', 'label': 'Видео (автовставка)'})}, verbose_name='Медиа контент')),
                ('content', wagtail.fields.RichTextField(blank=True, verbose_name='Содержание')),
                ('gallery', wagtail.fields.StreamField([('image', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {'label': 'Изображение галереи'})}, verbose_name='Галерея')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
            bases=('wagtailcore.page',),
        ),
    ]
