# Generated by Django 5.2.6 on 2025-09-13 13:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspage',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='newspage',
            name='category',
            field=models.CharField(choices=[('company', 'Новости компании'), ('tech', 'Технологии'), ('projects', 'Проекты'), ('events', 'События'), ('awards', 'Награды')], default='company', max_length=250, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='content',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 1), ('quote', 2), ('embed', 3), ('divider', 4)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'code', 'blockquote'], 'label': 'Абзац текста', 'template': 'blocks/paragraph_block.html'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'template': 'blocks/image_block.html'}), 2: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Цитата', 'template': 'blocks/quote_block.html'}), 3: ('wagtail.blocks.static_block.StaticBlock', (), {'label': 'Видео', 'template': 'blocks/embed_block.html'}), 4: ('wagtail.blocks.static_block.StaticBlock', (), {'label': 'Разделитель', 'template': 'blocks/divider_block.html'})}, verbose_name='Содержание новости'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Превью'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='intro',
            field=models.TextField(blank=True, help_text='1-3 предложения для анонса', verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='Важная новость'),
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('publish_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('headline', models.CharField(blank=True, verbose_name='Новостной заголовок')),
                ('news_per_page', models.PositiveIntegerField(default=6, verbose_name='Количество новостей на странице')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Превью')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
