# Generated by Django 5.2.6 on 2025-09-17 10:25

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newspage_options_newspage_category_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsindexpage',
            options={'verbose_name': 'Лента новостей', 'verbose_name_plural': 'Ленты новостей'},
        ),
        migrations.RemoveField(
            model_name='newsindexpage',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='newsindexpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='newsindexpage',
            name='news_per_page',
        ),
        migrations.RemoveField(
            model_name='newsindexpage',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='is_important',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Введение'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='excerpt',
            field=models.CharField(default='ну описание', max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='read_time',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Время чтения (мин)'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='content',
            field=wagtail.fields.RichTextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение'),
        ),
    ]
