# Generated by Django 5.2.6 on 2025-09-17 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newspage_excerpt_alter_newspage_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsindexpage',
            name='items_per_page',
            field=models.PositiveIntegerField(default=9, verbose_name='Новостей на странице'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение'),
        ),
    ]
