# Generated by Django 5.2.6 on 2025-09-17 20:19

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsindexpage_items_per_page_alter_newspage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='read_time',
        ),
        migrations.AddField(
            model_name='newspage',
            name='category',
            field=models.CharField(choices=[('company', 'Новости компании'), ('tech', 'Технологии'), ('projects', 'Проекты'), ('events', 'События'), ('awards', 'Награды')], default='company', max_length=100, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='headline',
            field=models.CharField(default='Заголовок новости', max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='intro',
            field=models.TextField(blank=True, help_text='1-3 предложения для анонса', verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='content',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Содержание'),
        ),
    ]
