# Generated by Django 5.2.7 on 2025-10-09 09:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_newspage_excerpt_remove_newspage_read_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='gallery',
            field=wagtail.fields.StreamField([('image', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {'label': 'Изображение галереи'})}, verbose_name='Галерея'),
        ),
    ]
