# Generated by Django 5.2.7 on 2025-11-19 07:13

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newspage_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='media_content',
            field=wagtail.fields.StreamField([('image', 2), ('video', 4), ('embed', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {'label': 'Изображение'}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Ссылка на YouTube, Vimeo и т.д.', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('video_url', 3), ('caption', 1)]], {'label': 'Видео'}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Вставьте ссылку на видео (YouTube, Vimeo и т.д.)', 'label': 'Видео (автовставка)'})}, verbose_name='Медиа контент'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='read_time',
            field=models.PositiveIntegerField(default=1, help_text='Примерное время чтения статьи в минутах', verbose_name='Время чтения (мин)'),
        ),
    ]
