# Generated by Django 5.2.7 on 2025-11-10 12:26

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, verbose_name='Вступительный текст')),
                ('body', wagtail.fields.StreamField([('certificate', 8)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название сертификата', 'max_length': 200}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Кем выдан', 'max_length': 200}), 2: ('wagtail.blocks.DateBlock', (), {'label': 'Дата выдачи'}), 3: ('wagtail.blocks.DateBlock', (), {'label': 'Действует до', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Текст бейджа (например: ISO, Gold Partner)', 'max_length': 50, 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('rose', 'Розовый'), ('emerald', 'Зелёный'), ('violet', 'Фиолетовый'), ('amber', 'Жёлтый'), ('blue', 'Синий')], 'label': 'Цвет бейджа'}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Превью (рекомендуется 600×800)', 'required': False}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'PDF сертификата', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('issuer', 1), ('issue_date', 2), ('expiry_date', 3), ('badge_text', 4), ('badge_color', 5), ('thumbnail', 6), ('document', 7)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
