# Generated by Django 5.2.8 on 2025-12-01 11:42

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, verbose_name='Вступительный текст')),
                ('body', wagtail.fields.StreamField([('certificate', 5)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название сертификата', 'max_length': 200}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Кем выдан', 'max_length': 200}), 2: ('wagtail.blocks.DateBlock', (), {'label': 'Дата выдачи'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Превью сертификата', 'required': False}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'PDF сертификата', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('issuer', 1), ('issue_date', 2), ('thumbnail', 3), ('document', 4)]], {})})),
            ],
            options={
                'verbose_name': "Страница 'Сертификаты'",
                'verbose_name_plural': "Страница 'Сертификатов' ",
            },
            bases=('wagtailcore.page',),
        ),
    ]
