# Generated by Django 5.2.7 on 2025-11-11 09:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatesindexpage',
            name='body',
            field=wagtail.fields.StreamField([('certificate', 5)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название сертификата', 'max_length': 200}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Кем выдан', 'max_length': 200}), 2: ('wagtail.blocks.DateBlock', (), {'label': 'Дата выдачи'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Превью сертификата', 'required': False}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'PDF сертификата', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('issuer', 1), ('issue_date', 2), ('thumbnail', 3), ('document', 4)]], {})}),
        ),
    ]
