# Generated by Django 5.2.7 on 2025-11-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificatesindexpage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatesindexpage',
            options={'verbose_name': "Страница 'Сертификаты'", 'verbose_name_plural': "Страница 'Сертификатов' "},
        ),
    ]
