# Generated by Django 5.2.6 on 2025-09-24 07:21

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmessage',
            name='created_at',
            field=models.DateTimeField(default=utils.get_tumen_time, verbose_name='Дата создания'),
        ),
    ]
