# Generated by Django 5.2.6 on 2025-09-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedbackmessage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmessage',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Просмотрено'),
        ),
    ]
