# Generated by Django 5.2.7 on 2025-10-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedbackmessage_is_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmessage',
            name='company',
        ),
        migrations.RemoveField(
            model_name='feedbackmessage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='feedbackmessage',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='feedbackmessage',
            name='service_of_interest',
        ),
    ]
