# Generated by Django 5.2.6 on 2025-09-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminnotification',
            name='level',
        ),
    ]
