# Generated by Django 5.2.6 on 2025-09-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_adminnotification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='title',
            field=models.CharField(default='', verbose_name='Наименование'),
            preserve_default=False,
        ),
    ]
