# Generated by Django 5.2.7 on 2025-11-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_adminnotification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
    ]
