# Generated by Django 5.2.7 on 2025-10-09 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='career_button_link',
            field=models.ForeignKey(blank=True, help_text='Выберите страницу для ссылки на консультацию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
