# Generated by Django 5.2.7 on 2025-10-09 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutpage_career_button_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='career_button_link',
            new_name='career_button_link1',
        ),
    ]
