# Generated by Django 5.2.7 on 2025-10-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_rename_career_button_link_aboutpage_career_button_link1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='career_button_link1',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='career_button_link',
            field=models.CharField(blank=True, default='#', help_text="Ссылка для кнопки в секции 'Карьера'", max_length=255),
        ),
    ]
