# Generated by Django 5.2.7 on 2025-10-14 10:23

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_remove_aboutpage_achievements_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='content',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='achievements',
            field=wagtail.fields.StreamField([('main_achievement', 5), ('additional_achievement', 8)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Выберите изображение для иконки (рекомендуемый размер: 50x50px)', 'label': 'Иконка', 'required': False}), 1: ('wagtail.blocks.IntegerBlock', (), {'default': 0, 'label': 'Числовое значение'}), 2: ('wagtail.blocks.CharBlock', (), {'blank': True, 'default': '+', 'label': "Суффикс (например, '+' или '%')", 'max_length': 10}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Краткое название', 'max_length': 100}), 4: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'label': 'Описание достижения'}), 5: ('wagtail.blocks.StructBlock', [[('icon', 0), ('value', 1), ('suffix', 2), ('label', 3), ('description', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Числовое значение или текст', 'max_length': 10}), 7: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Заголовок достижения', 'max_length': 100}), 8: ('wagtail.blocks.StructBlock', [[('value', 6), ('title', 7), ('description', 4)]], {})}, verbose_name='Достижения'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='approach_description_1',
            field=wagtail.fields.RichTextField(blank=True, default='Полная интеграция ИТ-систем в бизнес-процессы компании для повышения прозрачности и управляемости', help_text='Первый пункт описания подхода'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='approach_description_2',
            field=wagtail.fields.RichTextField(blank=True, default='Переход на управление в режиме реального времени и постоянное внедрение улучшений для устойчивого роста', help_text='Второй пункт описания подхода'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='approach_title',
            field=models.CharField(blank=True, default='Комплексный подход', help_text="Заголовок секции 'Подход и ценность'", max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='career_button_link',
            field=models.CharField(blank=True, default='#', help_text="Ссылка для кнопки в секции 'Карьера'", max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='career_button_text',
            field=models.CharField(blank=True, default='Подробнее', help_text="Текст кнопки в секции 'Карьера'", max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='career_description',
            field=wagtail.fields.RichTextField(blank=True, default='ALMA — команда профессионалов, работающих с крупными нефтегазовыми компаниями. У нас гибкая система бонусов, удалёнка, рост, открытые отношения внутри команды.', help_text="Описание секции 'Карьера'"),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='career_items',
            field=models.TextField(blank=True, default='Проектное управление\nФинансовый анализ\nУправление производством\nИнженерные решения\nРазработка интерфейсов\nСерверная разработка\nUI/UX-дизайн\nГрафический дизайн\nАнализ данных\nЦифровой маркетинг', help_text='Список направлений карьеры (каждый пункт с новой строки)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='career_title',
            field=models.CharField(blank=True, default='Карьера в ALMA', help_text="Заголовок секции 'Карьера'", max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contact_button_link',
            field=models.CharField(blank=True, default='#', help_text="Ссылка для кнопки в секции 'Контакты'", max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contact_button_text',
            field=models.CharField(blank=True, default='Отправить', help_text="Текст кнопки в секции 'Контакты'", max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contact_description',
            field=models.TextField(blank=True, default='Нажимая кнопку, я принимаю соглашение о конфиденциальности и соглашаюсь с обработкой персональных данных', help_text="Описание секции 'Контакты'"),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contact_privacy_note',
            field=models.TextField(blank=True, default='This site is protected by reCAPTCHA and the Google Privacy Policy and Terms of Service apply.', help_text='Примечание о конфиденциальности'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contact_title',
            field=models.CharField(blank=True, default='Связаться с нами', help_text="Заголовок секции 'Контакты'", max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_button_link',
            field=models.CharField(blank=True, default='#contact', help_text='Ссылка для кнопки в секции Hero', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_button_text',
            field=models.CharField(blank=True, default='Связаться с нами', help_text='Текст кнопки в секции Hero', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_description_1',
            field=wagtail.fields.RichTextField(blank=True, default='Группа ALMA — надёжный партнёр нефтегазовых и нефтесервисных компаний в РФ и за рубежом', help_text='Первое описание компании в секции Hero'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_description_2',
            field=wagtail.fields.RichTextField(blank=True, default='Разрабатываем собственные программные решения для отраслей', help_text='Второе описание компании в секции Hero'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_description_3',
            field=wagtail.fields.RichTextField(blank=True, default='Внедряем ИИ и ML в процессы управления производством, предиктивного анализа, автоматизации', help_text='Третье описание компании в секции Hero'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text="Изображение для секции 'О компании'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_service_list',
            field=models.TextField(blank=True, default='IT-компании и ИТ-подразделения\nПромышленные и технологические предприятия\nОрганизации, стремящиеся повысить эффективность управления', help_text='Список сервисов и услуг (каждый пункт с новой строки)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title',
            field=models.CharField(blank=True, default='О компании', help_text="Заголовок секции 'О компании'", max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='industries_title',
            field=models.CharField(blank=True, default='Отрасли применения', help_text="Заголовок секции 'Отрасли'", max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='industry_01',
            field=models.CharField(blank=True, default='Нефтегазовая промышленность', help_text='Отрасль 01', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='industry_02',
            field=models.CharField(blank=True, default='Химическая промышленность', help_text='Отрасль 02', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='industry_03',
            field=models.CharField(blank=True, default='Металлургическая промышленность', help_text='Отрасль 03', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='industry_04',
            field=models.CharField(blank=True, default='Гражданское строительство', help_text='Отрасль 04', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='industry_05',
            field=models.CharField(blank=True, default='Пищевая промышленность', help_text='Отрасль 05', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='industry_06',
            field=models.CharField(blank=True, default='Электроэнергетика', help_text='Отрасль 06', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='metric_presence_label',
            field=models.CharField(blank=True, default='Глобальное присутствие', help_text='Заголовок метрики присутствия', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='metric_presence_value',
            field=models.CharField(blank=True, default='Россия / международно', help_text='Значение метрики присутствия', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='metric_projects_label',
            field=models.CharField(blank=True, default='Реализованных проектов', help_text='Заголовок метрики проектов', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='metric_projects_value',
            field=models.CharField(blank=True, default='35+', help_text='Значение метрики проектов', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='metric_year_label',
            field=models.CharField(blank=True, default='Год основания компании', help_text='Заголовок метрики года', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='metric_year_value',
            field=models.CharField(blank=True, default='2017', help_text='Значение метрики года', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='trust_title',
            field=models.CharField(blank=True, default='Нам доверяют', help_text="Заголовок секции 'Метрики'", max_length=255),
        ),
    ]
