# Generated by Django 5.2.7 on 2025-10-31 10:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_aboutpage_global_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='global_presence',
            field=wagtail.fields.StreamField([('presence', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Глобальное присутствие', 'label': 'Заголовок', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link', 'superscript'], 'label': 'Описание', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Рекомендуемый размер: квадратное или 1x1', 'label': 'Изображение для локации', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2)]], {})}, verbose_name='Глобальное присутствие'),
        ),
    ]
