# Generated by Django 5.2.6 on 2025-09-24 10:05

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(default=utils.get_tumen_time, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('resume', models.ForeignKey(blank=True, help_text='Загрузите резюме в формате PDF, DOC или DOCX', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.document', verbose_name='Файл резюме')),
            ],
            options={
                'verbose_name': 'Резюме',
                'ordering': ['-created_at'],
            },
        ),
    ]
