# Generated by Django 5.2.6 on 2025-09-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='resume',
            field=models.FileField(blank=True, help_text='Загрузите резюме в формате PDF, DOC или DOCX', null=True, upload_to='resumes/%Y/%m/%d/', verbose_name='Файл резюме'),
        ),
    ]
