# Generated by Django 5.2.6 on 2025-09-26 08:33

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_alter_vacancy_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='resume',
            field=models.FileField(blank=True, help_text='Загрузите резюме в формате PDF, DOC или DOCX', null=True, upload_to='resumes/%Y/%m/%d/', validators=[utils.validate_file_extension], verbose_name='Файл резюме'),
        ),
    ]
