# Generated by Django 5.2.6 on 2025-09-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_alter_vacancy_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='titile',
            field=models.CharField(default='', verbose_name='Вакансия'),
            preserve_default=False,
        ),
    ]
