# Generated by Django 5.2.6 on 2025-09-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0005_vacancy_titile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='titile',
            new_name='title',
        ),
    ]
