# Generated by Django 5.2.6 on 2025-09-26 11:43

import django.db.models.deletion
import core.utils as utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_rename_titile_vacancy_title'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='resume_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancy_resumes', to='wagtaildocs.document', verbose_name='Резюме (документ Wagtail)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/%d/', validators=[utils.validate_file_extension], verbose_name='Резюме (оригинальное)'),
        ),
    ]
