# Generated by Django 5.2.6 on 2025-09-29 04:53

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0007_vacancy_resume_document_alter_vacancy_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='resume_document',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/%d/', validators=[utils.validate_file_extension], verbose_name='Резюме'),
        ),
    ]
