# Generated by Django 5.2.6 on 2025-09-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0008_remove_vacancy_resume_document_alter_vacancy_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/%d/', verbose_name='Резюме'),
        ),
    ]
