# Generated by Django 5.2.6 on 2025-09-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0009_alter_vacancy_options_alter_vacancy_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='resume_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка для скачивания резюме'),
        ),
    ]
