# Generated by Django 5.2.7 on 2025-10-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0010_vacancy_resume_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Отклик на вакансию', 'verbose_name_plural': 'Отклики на вакансии'},
        ),
    ]
