# Generated by Django 5.2.6 on 2025-09-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Email'), ('address', 'Адрес'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram'), ('other', 'Другое')], max_length=20, verbose_name='Тип контакта')),
                ('value', models.CharField(max_length=250, verbose_name='Значение')),
                ('label', models.CharField(blank=True, help_text="Например: 'Основной телефон', 'Электронная почта'", max_length=20, verbose_name='Подпись контакта')),
                ('icon', models.CharField(blank=True, help_text="Название иконки (например: 'phone', 'email')", max_length=50, verbose_name='Иконка')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной контакт')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Контакт компании',
                'verbose_name_plural': 'Контакты компании',
                'ordering': ['order', 'contact_type'],
            },
        ),
    ]
