# Generated by Django 5.2.7 on 2025-10-08 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('map_info', models.TextField(blank=True, verbose_name='Инструкции для карты (например, Embed-код)')),
                ('contact_form_text', models.TextField(blank=True, verbose_name='Текст для формы')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='Юридическое название')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('ogrn', models.CharField(blank=True, max_length=13, verbose_name='ОГРН')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
