# Generated by Django 5.2.8 on 2025-12-01 12:39

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('address', models.TextField(blank=True, help_text='Полный адрес с индексом', verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('work_hours', models.CharField(blank=True, max_length=200, verbose_name='Режим работы')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='Полное наименование')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('okpo', models.CharField(blank=True, max_length=10, verbose_name='ОКПО')),
                ('okved_codes', wagtail.fields.RichTextField(blank=True, verbose_name='Коды ОКВЭД')),
                ('it_activity_codes', wagtail.fields.RichTextField(blank=True, verbose_name='Коды ИТ-деятельности (Приказ Минцифры №449)')),
                ('price_info', wagtail.fields.RichTextField(blank=True, verbose_name='Информация о стоимости услуг')),
                ('software_rights', wagtail.fields.RichTextField(blank=True, verbose_name='Правообладание программным обеспечением')),
                ('technologies', wagtail.fields.RichTextField(blank=True, verbose_name='Технологический стек')),
                ('map_embed_code', models.TextField(blank=True, verbose_name='Код встраивания карты')),
                ('additional_info', wagtail.fields.RichTextField(blank=True, verbose_name='Дополнительная информация')),
                ('dynamic_blocks', wagtail.fields.StreamField([('heading', 2), ('info_card', 6), ('technology_item', 9), ('legal_document', 12), ('contact_method', 16), ('social_link', 20), ('map_block', 23), ('pricing_table', 29), ('accordion', 35)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок'}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Подзаголовок', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1)]], {'icon': 'title', 'label': 'Заголовок раздела'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок карточки'}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Содержание'}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: fas fa-phone, fas fa-envelope', 'label': 'Класс иконки', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 3), ('content', 4), ('icon_class', 5)]], {'icon': 'doc-full', 'label': 'Информационная карточка'}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Название технологии'}), 8: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('name', 7), ('description', 8)]], {'icon': 'code', 'label': 'Технология'}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Название документа'}), 11: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Файл', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 10), ('content', 4), ('file', 11)]], {'icon': 'doc-full-inverse', 'label': 'Юридический документ'}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('phone', 'Телефон'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('viber', 'Viber')], 'label': 'Тип контакта'}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Значение'}), 15: ('wagtail.blocks.CharBlock', (), {'label': 'Описание', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('type', 13), ('value', 14), ('description', 15)]], {'icon': 'user', 'label': 'Способ связи'}), 17: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('vk', 'ВКонтакте'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('viber', 'Viber'), ('skype', 'Skype')], 'label': 'Платформа'}), 18: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка'}), 19: ('wagtail.blocks.CharBlock', (), {'label': 'Текст ссылки', 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('platform', 17), ('url', 18), ('text', 19)]], {'icon': 'site', 'label': 'Социальная сеть'}), 21: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок карты'}), 22: ('wagtail.blocks.TextBlock', (), {'label': 'Код для вставки карты'}), 23: ('wagtail.blocks.StructBlock', [[('title', 21), ('embed_code', 22), ('description', 8)]], {'icon': 'site', 'label': 'Карта'}), 24: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок таблицы'}), 25: ('wagtail.blocks.CharBlock', (), {'label': 'Услуга'}), 26: ('wagtail.blocks.CharBlock', (), {'label': 'Стоимость'}), 27: ('wagtail.blocks.StructBlock', [[('service_name', 25), ('description', 8), ('price', 26)]], {'label': 'Услуга'}), 28: ('wagtail.blocks.ListBlock', (27,), {}), 29: ('wagtail.blocks.StructBlock', [[('title', 24), ('services', 28)]], {'icon': 'table', 'label': 'Таблица цен'}), 30: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок аккордеона'}), 31: ('wagtail.blocks.CharBlock', (), {'label': 'Вопрос'}), 32: ('wagtail.blocks.RichTextBlock', (), {'label': 'Ответ'}), 33: ('wagtail.blocks.StructBlock', [[('question', 31), ('answer', 32)]], {'label': 'Элемент'}), 34: ('wagtail.blocks.ListBlock', (33,), {}), 35: ('wagtail.blocks.StructBlock', [[('title', 30), ('items', 34)]], {'icon': 'list-ul', 'label': 'Аккордеон FAQ'})}, verbose_name='Динамические блоки')),
            ],
            options={
                'verbose_name': 'Страница контактов',
                'verbose_name_plural': 'Страницы контактов',
            },
            bases=('wagtailcore.page',),
        ),
    ]
