# Generated by Django 5.2.7 on 2025-10-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': "Страница 'Контакты компании'", 'verbose_name_plural': "Страницы 'Контакты компании'"},
        ),
    ]
