# Generated by Django 5.2.12 on 2026-04-21 06:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='social_links',
            field=wagtail.fields.StreamField([('social', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Платформа', 'max_length': 50}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Ссылка (например, https://facebook.com или #contact)', 'max_length': 200}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка (например, facebook, twitter)'}), 3: ('wagtail.blocks.StructBlock', [[('platform', 0), ('href', 1), ('icon', 2)]], {'label': 'Социальная сеть'})}, verbose_name='Социальные сети'),
        ),
    ]
