# Generated by Django 5.2.6 on 2025-09-15 22:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_formfield_page_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='certifications',
            field=wagtail.fields.StreamField([('cert', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название сертификации', 'max_length': 100}), 1: ('wagtail.blocks.StructBlock', [[('title', 0)]], {'label': 'Сертификация'})}, verbose_name='Сертификации'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='company_links',
            field=wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 100}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Якорь (например, #about)', 'max_length': 100, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('url', 1), ('anchor', 2)]], {'label': 'Ссылка компании'})}, verbose_name='Ссылки компании'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='industries_links',
            field=wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 100}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Якорь', 'max_length': 100, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('url', 1), ('anchor', 2)]], {'label': 'Ссылка отрасли'})}, verbose_name='Ссылки отраслей'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='services_links',
            field=wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 100}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Якорь (например, #services)', 'max_length': 100, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('url', 1), ('anchor', 2)]], {'label': 'Ссылка услуги'})}, verbose_name='Ссылки услуг'),
        ),
    ]
