# Generated by Django 5.2.12 on 2026-04-21 07:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_footersettings_social_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='social_links',
            field=wagtail.fields.StreamField([('item', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции', 'max_length': 100, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Название соцсети', 'max_length': 50}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Ссылка', 'max_length': 200}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка (например, facebook, twitter)'}), 4: ('wagtail.blocks.StructBlock', [[('text', 1), ('href', 2), ('icon', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 5)]], {'label': 'Секция соцсетей'})}, verbose_name='Социальные сети'),
        ),
    ]
