# Generated by Django 5.2.6 on 2025-09-16 08:41

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_footersettings_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsettings',
            name='callback_button_text',
            field=models.CharField(blank=True, default='Заказать звонок', max_length=50, verbose_name='Текст кнопки обратного звонка'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='callback_button_url',
            field=models.URLField(blank=True, verbose_name='Ссылка для кнопки обратного звонка'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='contact_description',
            field=models.TextField(blank=True, verbose_name='Описание контактной информации'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='social_links',
            field=wagtail.fields.StreamField([('social', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Платформа (facebook, twitter, linkedin)', 'max_length': 50}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка'}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'facebook', 'label': 'Иконка (например, facebook, twitter)', 'max_length': 50}), 3: ('wagtail.blocks.StructBlock', [[('platform', 0), ('url', 1), ('icon', 2)]], {'label': 'Социальная сеть'})}, verbose_name='Социальные сети'),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='map_embed_code',
            field=models.TextField(blank=True, help_text='HTML код для встраивания карты (например, Google Maps)', verbose_name='Код карты'),
        ),
    ]
