# Generated by Django 5.2.6 on 2025-09-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_contactsettings_callback_button_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsettings',
            name='callback_button_text',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='callback_button_url',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='map_embed_code',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='secondary_email',
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='form_privacy_text',
            field=models.TextField(default="Нажимая кнопку, я принимаю <a href='/privacy-policy/'>соглашение о конфиденциальности</a> и соглашаюсь с обработкой персональных данных", verbose_name='Текст политики конфиденциальности'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='form_recaptcha_text',
            field=models.TextField(default="This site is protected by reCAPTCHA and the Google <a href='https://policies.google.com/privacy' target='_blank'>Privacy Policy</a> and <a href='https://policies.google.com/terms' target='_blank'>Terms of Service</a> apply.", verbose_name='Текст reCAPTCHA'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='form_title',
            field=models.CharField(default='Свяжитесь с нами', max_length=100, verbose_name='Заголовок формы'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='title',
            field=models.CharField(default='Контакты', max_length=100, verbose_name='Заголовок секции'),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='contact_description',
            field=models.TextField(blank=True, verbose_name='Описание контактов'),
        ),
    ]
