# Generated by Django 5.2.6 on 2025-09-16 08:50

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_contactsettings_callback_button_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsettings',
            name='contact_description',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='form_privacy_text',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='form_recaptcha_text',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='social_links',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='title',
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='map_placeholder_text',
            field=models.TextField(default='г. Москва, ул. Тверская, д. 15', verbose_name='Текст под картой'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='privacy_policy_text',
            field=models.TextField(default="Нажимая кнопку, вы соглашаетесь с <a href='/privacy-policy/'>политикой обработки персональных данных</a>", verbose_name='Текст политики конфиденциальности'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Дополнительный email'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='section_description',
            field=models.TextField(default='Готовы обсудить автоматизацию вашего бизнеса? Свяжитесь с нашими экспертами для получения персональной консультации.', verbose_name='Описание секции'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='section_title',
            field=models.CharField(default='Связаться с нами', max_length=100, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='services',
            field=wagtail.fields.StreamField([('service', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название услуги', 'max_length': 100})}, verbose_name='Список услуг'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='working_hours',
            field=models.TextField(default='Пн-Пт: 9:00 - 18:00, Сб-Вс: по договоренности', verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='form_title',
            field=models.CharField(default='Оставить заявку', max_length=100, verbose_name='Заголовок формы'),
        ),
    ]
