# Generated by Django 5.2.6 on 2025-09-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_contactsettings_contact_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='go_live_at',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='has_unpublished_changes',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='live',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='live_revision',
        ),
    ]
