# Generated by Django 5.2.6 on 2025-09-16 09:23

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_sitesettings_expire_at_sitesettings_expired_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsettings',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='go_live_at',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='has_unpublished_changes',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='live',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='go_live_at',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='has_unpublished_changes',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='live',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='live_revision',
        ),
        migrations.AddField(
            model_name='footersettings',
            name='contact_button_href',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка кнопки (например, #contact или /contact)'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='contact_button_text',
            field=models.CharField(default='Связаться с нами', max_length=50, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='company_links',
            field=wagtail.fields.StreamField([('link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Ссылка (например, /about или #contact)', 'max_length': 200}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('href', 1)]], {'label': 'Ссылка компании'})}, verbose_name='Ссылки компании'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='industries_links',
            field=wagtail.fields.StreamField([('link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Ссылка (например, /industries или #industries)', 'max_length': 200}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('href', 1)]], {'label': 'Ссылка отрасли'})}, verbose_name='Ссылки отраслей'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='services_links',
            field=wagtail.fields.StreamField([('link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Ссылка (например, /services или #services)', 'max_length': 200}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('href', 1)]], {'label': 'Ссылка услуги'})}, verbose_name='Ссылки услуг'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='social_links',
            field=wagtail.fields.StreamField([('social', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Платформа', 'max_length': 50}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Ссылка (например, https://facebook.com или #contact)', 'max_length': 200}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Иконка (например, facebook, twitter)', 'max_length': 50}), 3: ('wagtail.blocks.StructBlock', [[('platform', 0), ('href', 1), ('icon', 2)]], {'label': 'Социальная сеть'})}, verbose_name='Социальные сети'),
        ),
    ]
