# Generated by Django 5.2.6 on 2025-09-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_contactsettings_expire_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='go_live_at',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='has_unpublished_changes',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='live',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='live_revision',
        ),
    ]
