# Generated by Django 5.2.6 on 2025-09-16 09:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_footersettings_expire_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='company_links',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='industries_links',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='services_links',
        ),
        migrations.AddField(
            model_name='footersettings',
            name='company_section',
            field=wagtail.fields.StreamField([('item', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции', 'max_length': 100, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Текст ссылки', 'max_length': 100}), 2: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Ссылка (например, /about или #contact)', 'max_length': 200}), 3: ('wagtail.blocks.StructBlock', [[('text', 1), ('href', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 4)]], {'label': 'Секция компании'})}, verbose_name='Секции компании'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='services_section',
            field=wagtail.fields.StreamField([('item', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции', 'max_length': 100, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Текст ссылки', 'max_length': 100}), 2: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Ссылка (например, /services или #services)', 'max_length': 200}), 3: ('wagtail.blocks.StructBlock', [[('text', 1), ('href', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 4)]], {'label': 'Секция услуг'})}, verbose_name='Секции услуг'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='solutions_section',
            field=wagtail.fields.StreamField([('item', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции', 'max_length': 100, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Текст ссылки', 'max_length': 100}), 2: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Ссылка (например, /solutions или #solutions)', 'max_length': 200}), 3: ('wagtail.blocks.StructBlock', [[('text', 1), ('href', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 4)]], {'label': 'Секция решений'})}, verbose_name='Секции решений'),
        ),
    ]
