# Generated by Django 5.2.6 on 2025-09-16 10:00

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_contactsettings_expire_at_contactsettings_expired_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Контакты', max_length=100)),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('map_info', models.TextField(blank=True, verbose_name='Инструкции для карты (например, координаты или Embed-код)')),
                ('contact_form_text', wagtail.fields.RichTextField(blank=True, verbose_name='Текст для формы')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='Юридическое название компании')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('ogrn', models.CharField(blank=True, max_length=13, verbose_name='ОГРН')),
            ],
            options={
                'verbose_name': 'Страница контактов',
                'verbose_name_plural': 'Страницы контактов',
            },
        ),
    ]
