# Generated by Django 5.2.6 on 2025-09-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_contactpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='map_info',
            field=models.TextField(blank=True, default='<iframe src="https://yandex.ru/map-widget/v1/?ll=65.5370,57.1527&z=12" width="100%" height="100%"></iframe>', verbose_name='Инструкции для карты (например, координаты или Embed-код)'),
        ),
    ]
