# Generated by Django 5.2.6 on 2025-09-16 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_contactpage_map_info'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={},
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='title',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=3232, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_form_text',
            field=models.TextField(blank=True, verbose_name='Текст для формы'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Юридическое название'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='map_info',
            field=models.TextField(blank=True, verbose_name='Инструкции для карты (например, Embed-код)'),
        ),
    ]
