# Generated by Django 5.2.6 on 2025-09-22 07:27

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_contactpage_options_remove_contactpage_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headersettings',
            name='site_subtitle',
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='consultation_button_text',
            field=models.CharField(blank=True, default='Оставить заявку', max_length=50, verbose_name='Текст кнопки консультации'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='nav_items',
            field=wagtail.fields.StreamField([('nav_item', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название пункта', 'max_length': 50}), 1: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Внешняя ссылка', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Выпадающее меню', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Название подпункта', 'max_length': 50}), 5: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('name', 4), ('page', 1), ('external_url', 2), ('description', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Элементы выпадающего меню', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('name', 0), ('page', 1), ('external_url', 2), ('is_dropdown', 3), ('dropdown_items', 7)]], {'label': 'Пункт меню'})}, verbose_name='Пункты меню'),
        ),
    ]
