# Generated by Django 5.2.6 on 2025-09-22 07:38

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_headersettings_site_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headersettings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='headersettings',
            name='consultation_button_url',
            field=models.URLField(blank=True, default='#contact', help_text='URL для кнопки консультации', verbose_name='Ссылка кнопки консультации'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='nav_items',
            field=wagtail.fields.StreamField([('nav_item', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название пункта', 'max_length': 50}), 1: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Внешняя ссылка', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Выпадающее меню', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: Автоматизация бизнеса', 'label': 'Название группы', 'max_length': 100}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Название подпункта', 'max_length': 50}), 6: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 7: ('wagtail.blocks.TextBlock', (), {'help_text': 'Вставьте SVG код для иконки', 'label': 'SVG код иконки', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('name', 5), ('page', 1), ('external_url', 2), ('description', 6), ('icon_svg', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'label': 'Элементы подменю'}), 10: ('wagtail.blocks.StructBlock', [[('group_title', 4), ('items', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Группы выпадающего меню', 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Название карточки', 'max_length': 100, 'required': False}), 13: ('wagtail.blocks.TextBlock', (), {'label': 'Описание карточки', 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'Подробнее', 'label': 'Текст кнопки', 'max_length': 50}), 15: ('wagtail.blocks.StructBlock', [[('title', 12), ('description', 13), ('page', 1), ('external_url', 2), ('button_text', 14)]], {'label': 'Карточка ссылки', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('name', 0), ('page', 1), ('external_url', 2), ('is_dropdown', 3), ('dropdown_groups', 11), ('card_link', 15)]], {'label': 'Пункт меню'})}, verbose_name='Пункты меню'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='site_title',
            field=models.CharField(blank=True, default='ДИО КОНСАЛТ', help_text='Название, которое отображается в header', max_length=100, verbose_name='Название сайта'),
        ),
    ]
