# Generated by Django 5.2.6 on 2025-09-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_headersettings_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headersettings',
            name='consultation_button_url',
            field=models.URLField(blank=True, default='#', help_text='URL для кнопки консультации', verbose_name='Ссылка кнопки консультации'),
        ),
    ]
