# Generated by Django 5.2.6 on 2025-09-22 09:39

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_headersettings_nav_items'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headersettings',
            name='consultation_button_text',
            field=models.CharField(default='Оставить заявку', help_text='Текст кнопки консультации', max_length=255),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='consultation_button_url',
            field=models.URLField(blank=True, help_text='URL для кнопки консультации'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Логотип сайта (рекомендуемый размер: 40x40px)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='nav_items',
            field=wagtail.fields.StreamField([('nav_item', 19)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название пункта меню', 'label': 'Название пункта*', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Выберите страницу для ссылки', 'label': 'Страница', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Укажите внешний URL, если страница не выбрана', 'label': 'Внешняя ссылка', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'Без подменю'), ('simple', 'Простое подменю'), ('grouped', 'Группированное подменю с карточкой')], 'help_text': 'Выберите тип подменю: без подменю, простое подменю или группированное подменю с карточкой', 'label': 'Тип меню*'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название подпункта', 'label': 'Название подпункта*', 'max_length': 255, 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('name', 4), ('page', 1), ('external_url', 2)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': 'Используется, если выбран тип "Простое подменю"', 'label': 'Простые элементы подменю', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: Автоматизация бизнеса', 'label': 'Название группы*', 'max_length': 255, 'required': True}), 8: ('wagtail.blocks.TextBlock', (), {'help_text': 'Краткое описание подпункта', 'label': 'Описание', 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'help_text': 'Вставьте SVG код для иконки', 'label': 'SVG код иконки', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('name', 4), ('page', 1), ('external_url', 2), ('description', 8), ('icon_svg', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Элементы подменю', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('group_title', 7), ('items', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Используется, если выбран тип "Группированное подменю"', 'label': 'Группы выпадающего меню', 'required': False}), 14: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Включить карточку ссылки', 'label': 'Включить карточку'}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название карточки', 'label': 'Название карточки', 'max_length': 255, 'required': False}), 16: ('wagtail.blocks.TextBlock', (), {'help_text': 'Описание карточки', 'label': 'Описание карточки', 'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'Подробнее', 'help_text': 'Текст кнопки на карточке', 'label': 'Текст кнопки*', 'max_length': 255, 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('enabled', 14), ('title', 15), ('description', 16), ('page', 1), ('external_url', 2), ('button_text', 17)]], {'label': 'Карточка ссылки', 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('name', 0), ('page', 1), ('external_url', 2), ('menu_type', 3), ('simple_dropdown_items', 6), ('dropdown_groups', 13), ('card_link', 18)]], {'icon': 'list-ul', 'label': 'Пункт меню'})}, null=True),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='site_title',
            field=models.CharField(blank=True, default='', help_text='Название сайта, отображаемое рядом с логотипом', max_length=255),
        ),
    ]
