# Generated by Django 5.2.6 on 2025-09-25 07:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_headersettings_nav_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headersettings',
            name='consultation_button_url',
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='nav_items',
            field=wagtail.fields.StreamField([('nav_item', 20)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название пункта меню', 'label': 'Название пункта', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Выберите страницу для ссылки', 'label': 'Страница', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Укажите внешний URL, если страница не выбрана', 'label': 'Внешняя ссылка', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('page', 1), ('external_url', 2)]], {'label': 'Ссылка', 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'Без подменю'), ('simple', 'Простое подменю'), ('grouped', 'Группированное подменю с карточкой')], 'help_text': 'Выберите тип подменю', 'label': 'Тип меню'}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название подпункта', 'label': 'Название подпункта', 'max_length': 255, 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('name', 5), ('link', 3)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'help_text': 'Используется при выборе "Простое подменю"', 'label': 'Простые элементы подменю', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: Автоматизация бизнеса', 'label': 'Название группы', 'max_length': 255, 'required': True}), 9: ('wagtail.blocks.TextBlock', (), {'help_text': 'Краткое описание подпункта', 'label': 'Описание', 'required': False}), 10: ('wagtail.blocks.TextBlock', (), {'help_text': 'Вставьте SVG код для иконки', 'label': 'SVG код иконки', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('name', 5), ('link', 3), ('description', 9), ('icon_svg', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'label': 'Элементы подменю', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('group_title', 8), ('items', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'help_text': 'Используется при выборе "Группированное подменю"', 'label': 'Группы выпадающего меню', 'max_num': 3, 'required': False}), 15: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Включить карточку ссылки', 'label': 'Включить карточку', 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название карточки', 'label': 'Название карточки', 'max_length': 255, 'required': False}), 17: ('wagtail.blocks.TextBlock', (), {'help_text': 'Описание карточки', 'label': 'Описание карточки', 'required': False}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Подробнее', 'help_text': 'Текст кнопки на карточке', 'label': 'Текст кнопки', 'max_length': 255, 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('enabled', 15), ('title', 16), ('description', 17), ('link', 3), ('button_text', 18)]], {'label': 'Карточка ссылки', 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('name', 0), ('link', 3), ('menu_type', 4), ('simple_dropdown_items', 7), ('dropdown_groups', 14), ('card_link', 19)]], {'icon': 'list-ul', 'label': 'Пункт меню'})}, null=True),
        ),
    ]
