# Generated by Django 5.2.6 on 2025-09-25 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_headersettings_consultation_button_url_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headersettings',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='go_live_at',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='has_unpublished_changes',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='live',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='live_revision',
        ),
        migrations.AddField(
            model_name='headersettings',
            name='consultation_page',
            field=models.ForeignKey(blank=True, help_text='Выберите страницу для кнопки консультации', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
