# Generated by Django 5.2.6 on 2025-09-29 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_headersettings_consultation_page_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='form_recipient_email',
            field=models.EmailField(blank=True, help_text='Email, на который будут отправляться заявки из формы.', max_length=254, verbose_name='Email для заявок'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='notification_users',
            field=models.ManyToManyField(blank=True, help_text='Выберите пользователей, которые будут получать уведомления в админке.', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи для уведомлений'),
        ),
    ]
