# Generated by Django 5.2.6 on 2025-10-01 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_remove_headersettings_consultation_button_url_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='consultation_page',
            field=models.ForeignKey(blank=True, help_text='Выберите страницу для ссылки на консультацию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
