# Generated by Django 5.2.6 on 2025-10-02 05:03

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_headersettings_consultation_page'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(blank=True, help_text="Заголовок секции 'О компании'", max_length=255)),
                ('hero_description', wagtail.fields.RichTextField(blank=True, help_text='Описание компании в секции Hero')),
                ('hero_button_text', models.CharField(blank=True, default='Связаться с нами', help_text='Текст кнопки в секции Hero', max_length=50)),
                ('hero_button_link', models.CharField(blank=True, help_text='Ссылка для кнопки в секции Hero (например, #contact)', max_length=255)),
                ('solutions_title', models.CharField(blank=True, default='Мы предлагаем / Направления', help_text="Заголовок секции 'Направления'", max_length=255)),
                ('solutions_items', wagtail.fields.StreamField([('solution', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок направления', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание направления', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {'label': 'Направление'})}, verbose_name='Направления')),
                ('industries_title', models.CharField(blank=True, default='Области применения', help_text="Заголовок секции 'Отрасли'", max_length=255)),
                ('industries_items', wagtail.fields.StreamField([('industry', 2)], blank=True, block_lookup={0: ('wagtail.blocks.IntegerBlock', (), {'label': 'Номер', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Название отрасли', 'max_length': 100, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('number', 0), ('title', 1)]], {'label': 'Отрасль'})}, verbose_name='Отрасли')),
                ('metrics_items', wagtail.fields.StreamField([('metric', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок метрики', 'max_length': 50, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Значение метрики', 'max_length': 50, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('label', 0), ('value', 1)]], {'label': 'Метрика'})}, verbose_name='Метрики')),
                ('approach_title', models.CharField(blank=True, default='Наш подход и ценность', help_text="Заголовок секции 'Подход и ценность'", max_length=255)),
                ('approach_description', wagtail.fields.RichTextField(blank=True, help_text='Описание подхода и ценности')),
                ('career_title', models.CharField(blank=True, default='Карьера в ALMA', help_text="Заголовок секции 'Карьера'", max_length=255)),
                ('career_description', wagtail.fields.RichTextField(blank=True, help_text="Описание секции 'Карьера'")),
                ('career_button_text', models.CharField(blank=True, default='Отправить резюме', help_text="Текст кнопки в секции 'Карьера'", max_length=50)),
                ('career_button_link', models.CharField(blank=True, help_text="Ссылка для кнопки в секции 'Карьера' (например, #contact)", max_length=255)),
                ('career_items', wagtail.fields.StreamField([('career_item', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Направление карьеры', 'max_length': 100, 'required': True})}, verbose_name='Направления карьеры')),
                ('hero_image', models.ForeignKey(blank=True, help_text="Изображение для секции 'О компании'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('industries_image', models.ForeignKey(blank=True, help_text="Изображение для секции 'Отрасли' (логотипы/партнеры)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': "Страница 'О компании'",
                'verbose_name_plural': "Страницы 'О компании'",
            },
            bases=('wagtailcore.page',),
        ),
    ]
