# Generated by Django 5.2.6 on 2025-10-02 05:14

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_aboutpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='approach_description',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_description',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='industries_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='industries_items',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='metrics_items',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='solutions_items',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='solutions_title',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='approach_description_1',
            field=wagtail.fields.RichTextField(blank=True, default='Полная интеграция ИТ-систем в бизнес-процессы компании для повышения прозрачности и управляемости', help_text='Первый пункт описания подхода'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='approach_description_2',
            field=wagtail.fields.RichTextField(blank=True, default='Переход на управление в режиме реального времени и постоянное внедрение улучшений для устойчивого роста', help_text='Второй пункт описания подхода'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contact_button_link',
            field=models.CharField(blank=True, default='#', help_text="Ссылка для кнопки в секции 'Контакты'", max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contact_button_text',
            field=models.CharField(blank=True, default='Отправить', help_text="Текст кнопки в секции 'Контакты'", max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contact_description',
            field=models.TextField(blank=True, default='Нажимая кнопку, я принимаю соглашение о конфиденциальности и соглашаюсь с обработкой персональных данных', help_text="Описание секции 'Контакты'"),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contact_privacy_note',
            field=models.TextField(blank=True, default='This site is protected by reCAPTCHA and the Google Privacy Policy and Terms of Service apply.', help_text='Примечание о конфиденциальности'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contact_title',
            field=models.CharField(blank=True, default='Связаться с нами', help_text="Заголовок секции 'Контакты'", max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_description_1',
            field=wagtail.fields.RichTextField(blank=True, default='Группа ALMA — надёжный партнёр нефтегазовых и нефтесервисных компаний в РФ и за рубежом', help_text='Первое описание компании в секции Hero'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_description_2',
            field=wagtail.fields.RichTextField(blank=True, default='Разрабатываем собственные программные решения для отраслей', help_text='Второе описание компании в секции Hero'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_description_3',
            field=wagtail.fields.RichTextField(blank=True, default='Внедряем ИИ и ML в процессы управления производством, предиктивного анализа, автоматизации', help_text='Третье описание компании в секции Hero'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_service_list',
            field=models.TextField(blank=True, default='IT-компании и ИТ-подразделения\nПромышленные и технологические предприятия\nОрганизации, стремящиеся повысить эффективность управления', help_text='Список сервисов и услуг (каждый пункт с новой строки)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='industry_01',
            field=models.CharField(blank=True, default='Нефтегазовая промышленность', help_text='Отрасль 01', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='industry_02',
            field=models.CharField(blank=True, default='Химическая промышленность', help_text='Отрасль 02', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='industry_03',
            field=models.CharField(blank=True, default='Металлургическая промышленность', help_text='Отрасль 03', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='industry_04',
            field=models.CharField(blank=True, default='Гражданское строительство', help_text='Отрасль 04', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='industry_05',
            field=models.CharField(blank=True, default='Пищевая промышленность', help_text='Отрасль 05', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='industry_06',
            field=models.CharField(blank=True, default='Электроэнергетика', help_text='Отрасль 06', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='metric_presence_label',
            field=models.CharField(blank=True, default='Глобальное присутствие', help_text='Заголовок метрики присутствия', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='metric_presence_value',
            field=models.CharField(blank=True, default='Россия / международно', help_text='Значение метрики присутствия', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='metric_projects_label',
            field=models.CharField(blank=True, default='Реализованных проектов', help_text='Заголовок метрики проектов', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='metric_projects_value',
            field=models.CharField(blank=True, default='35+', help_text='Значение метрики проектов', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='metric_year_label',
            field=models.CharField(blank=True, default='Год основания компании', help_text='Заголовок метрики года', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='metric_year_value',
            field=models.CharField(blank=True, default='2017', help_text='Значение метрики года', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='trust_title',
            field=models.CharField(blank=True, default='Нам доверяют', help_text="Заголовок секции 'Метрики'", max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='approach_title',
            field=models.CharField(blank=True, default='Комплексный подход', help_text="Заголовок секции 'Подход и ценность'", max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='career_button_link',
            field=models.CharField(blank=True, default='#', help_text="Ссылка для кнопки в секции 'Карьера'", max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='career_button_text',
            field=models.CharField(blank=True, default='Подробнее', help_text="Текст кнопки в секции 'Карьера'", max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='career_description',
            field=wagtail.fields.RichTextField(blank=True, default='ALMA — команда профессионалов, работающих с крупными нефтегазовыми компаниями. У нас гибкая система бонусов, удалёнка, рост, открытые отношения внутри команды.', help_text="Описание секции 'Карьера'"),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='career_items',
            field=models.TextField(blank=True, default='Проектное управление\nФинансовый анализ\nУправление производством\nИнженерные решения\nРазработка интерфейсов\nСерверная разработка\nUI/UX-дизайн\nГрафический дизайн\nАнализ данных\nЦифровой маркетинг', help_text='Список направлений карьеры (каждый пункт с новой строки)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_button_link',
            field=models.CharField(blank=True, default='#contact', help_text='Ссылка для кнопки в секции Hero', max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_title',
            field=models.CharField(blank=True, default='О компании', help_text="Заголовок секции 'О компании'", max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='industries_title',
            field=models.CharField(blank=True, default='Отрасли применения', help_text="Заголовок секции 'Отрасли'", max_length=255),
        ),
    ]
