# Generated by Django 5.2.6 on 2025-10-02 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_remove_aboutpage_approach_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPage',
        ),
    ]
