# Generated by Django 5.2.7 on 2025-10-06 10:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='achievements',
            field=wagtail.fields.StreamField([('main_achievement', 5), ('additional_achievement', 8)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Выберите изображение для иконки (рекомендуемый размер: 50x50px)', 'label': 'Иконка', 'required': False}), 1: ('wagtail.blocks.IntegerBlock', (), {'default': 0, 'label': 'Числовое значение'}), 2: ('wagtail.blocks.CharBlock', (), {'blank': True, 'default': '+', 'label': "Суффикс (например, '+' или '%')", 'max_length': 10}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Краткое название', 'max_length': 100}), 4: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'label': 'Описание достижения'}), 5: ('wagtail.blocks.StructBlock', [[('icon', 0), ('value', 1), ('suffix', 2), ('label', 3), ('description', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Числовое значение или текст', 'max_length': 10}), 7: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Заголовок достижения', 'max_length': 100}), 8: ('wagtail.blocks.StructBlock', [[('value', 6), ('title', 7), ('description', 4)]], {})}, verbose_name='Достижения'),
        ),
    ]
