# Generated by Django 5.2.7 on 2025-10-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_careerpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerpage',
            name='advantages',
        ),
        migrations.RemoveField(
            model_name='careerpage',
            name='directions',
        ),
        migrations.RemoveField(
            model_name='careerpage',
            name='values',
        ),
        migrations.AddField(
            model_name='careerpage',
            name='advantages_list',
            field=models.TextField(blank=True, default='Гибкий график работы\nВозможность удалёнки\nКонкурентные зарплаты\nПрофессиональный рост\nКорпоративное обучение', help_text='Список преимуществ (каждый пункт с новой строки)'),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='directions_list',
            field=models.TextField(blank=True, default='Проектное управление | Координация и контроль проектов\nФинансовый анализ | Анализ и планирование финансов\nРазработка ПО | Создание и поддержка программных решений', help_text="Список направлений (каждый пункт: 'Название | Описание' с новой строки)"),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='values_list',
            field=models.TextField(blank=True, default='Вовлечённость и работа на результат | Мы всегда ориентированы на достижение целей и вовлечены в процесс\nИнновации и развитие | Постоянно внедряем новые технологии для роста\nКомандная работа | Поддерживаем друг друга и делимся знаниями', help_text="Список ценностей (каждый пункт: 'Заголовок | Описание' с новой строки)"),
        ),
    ]
