# Generated by Django 5.2.7 on 2025-10-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_remove_careerpage_advantages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpage',
            name='office_address',
            field=models.CharField(blank=True, default='Москва, ул. Примерная, д. 1', help_text='Адрес офиса', max_length=255),
        ),
    ]
