# Generated by Django 5.2.7 on 2025-10-08 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_careerpage_office_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareerPage',
        ),
    ]
