# Generated by Django 5.2.7 on 2025-10-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_delete_aboutpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPage',
        ),
    ]
