# Generated by Django 5.2.7 on 2025-10-09 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_themesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsettings',
            options={'verbose_name': 'Контактов', 'verbose_name_plural': 'Контактов'},
        ),
        migrations.AlterModelOptions(
            name='footersettings',
            options={'verbose_name': 'Футер', 'verbose_name_plural': 'Футер'},
        ),
        migrations.AlterModelOptions(
            name='headersettings',
            options={'verbose_name': 'Хидер', 'verbose_name_plural': 'Хидер'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Сайта'},
        ),
        migrations.AlterModelOptions(
            name='themesettings',
            options={'verbose_name': 'Темы'},
        ),
    ]
