# Generated by Django 5.2.7 on 2025-10-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_alter_contactsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsettings',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Инофрмация о сайте'},
        ),
    ]
