# Generated by Django 5.2.8 on 2025-12-01 11:42

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service1CIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Введение')),
                ('items_per_page', models.PositiveIntegerField(default=9, verbose_name='Сервисов на странице')),
            ],
            options={
                'verbose_name': 'Лента сервисов 1С',
                'verbose_name_plural': 'Ленты сервисов 1С',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Single1CServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('category', models.CharField(choices=[('consulting', 'Консультации'), ('development', 'Разработка'), ('design', 'Дизайн'), ('support', 'Поддержка'), ('training', 'Обучение'), ('1c_services', '1С-сервисы')], default='1c_services', max_length=100, verbose_name='Категория')),
                ('headline', models.CharField(default='Заголовок сервиса 1С', max_length=255, verbose_name='Заголовок')),
                ('intro', models.TextField(blank=True, help_text='1-3 предложения для анонса', verbose_name='Краткое описание')),
                ('content', wagtail.fields.StreamField([('hero', 5), ('text', 7), ('what_we_do', 11), ('image_card', 14), ('card_grid', 22), ('metrics', 28), ('gallery', 32), ('video', 35), ('accordion', 41), ('cta', 46), ('supported_configurations', 53), ('system_requirements', 59)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок Hero', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Подзаголовок Hero', 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение Hero', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('image', 2), ('button_text', 3), ('button_link', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Текст'}), 7: ('wagtail.blocks.StructBlock', [[('content', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 9: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание', 'required': True}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение слева', 'required': True}), 11: ('wagtail.blocks.StructBlock', [[('title', 8), ('description', 9), ('image', 10)]], {}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': True}), 13: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('image', 12), ('title', 8), ('description', 13), ('button_text', 3), ('button_link', 4)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок сетки', 'required': True}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('numbered', 'Нумерованный'), ('bulleted', 'Маркированный'), ('icon_grid', 'Сетка с иконками'), ('image_grid', 'Сетка с изображениями')], 'label': 'Тип сетки'}), 17: ('wagtail.blocks.CharBlock', (), {'label': 'Название', 'required': True}), 18: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка (SVG)', 'required': False}), 19: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('title', 17), ('description', 13), ('icon', 18), ('image', 19)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'label': 'Элементы сетки'}), 22: ('wagtail.blocks.StructBlock', [[('title', 15), ('grid_type', 16), ('items', 21)]], {}), 23: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок метрик', 'required': True}), 24: ('wagtail.blocks.CharBlock', (), {'label': "Значение (например, '10+', '100')", 'required': True}), 25: ('wagtail.blocks.CharBlock', (), {'label': "Описание (например, 'Лет на рынке')", 'required': True}), 26: ('wagtail.blocks.StructBlock', [[('value', 24), ('label', 25), ('icon', 18)]], {}), 27: ('wagtail.blocks.ListBlock', (26,), {'label': 'Список метрик'}), 28: ('wagtail.blocks.StructBlock', [[('title', 23), ('items', 27)]], {}), 29: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок галереи', 'required': False}), 30: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 31: ('wagtail.blocks.ListBlock', (30,), {'label': 'Изображения'}), 32: ('wagtail.blocks.StructBlock', [[('title', 29), ('images', 31)]], {}), 33: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок видео', 'required': False}), 34: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Встраиваемое видео (YouTube, Vimeo и т.д.)', 'required': True}), 35: ('wagtail.blocks.StructBlock', [[('title', 33), ('video', 34)]], {}), 36: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок аккордеона', 'required': True}), 37: ('wagtail.blocks.CharBlock', (), {'label': 'Вопрос/Заголовок', 'required': True}), 38: ('wagtail.blocks.RichTextBlock', (), {'label': 'Ответ/Описание', 'required': True}), 39: ('wagtail.blocks.StructBlock', [[('question', 37), ('answer', 38)]], {}), 40: ('wagtail.blocks.ListBlock', (39,), {'label': 'Элементы аккордеона'}), 41: ('wagtail.blocks.StructBlock', [[('title', 36), ('items', 40)]], {}), 42: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок CTA', 'required': True}), 43: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание CTA', 'required': True}), 44: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'required': True}), 45: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка', 'required': False}), 46: ('wagtail.blocks.StructBlock', [[('title', 42), ('description', 43), ('button_text', 44), ('button_link', 45)]], {}), 47: ('wagtail.blocks.CharBlock', (), {'default': 'Поддерживаемые конфигурации', 'label': 'Заголовок блока конфигураций', 'required': True}), 48: ('wagtail.blocks.CharBlock', (), {'label': 'Название конфигурации', 'required': True}), 49: ('wagtail.blocks.CharBlock', (), {'label': 'Версия/Редакция', 'required': False}), 50: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Полностью протестировано'), ('partial', 'Частично поддерживается')], 'label': 'Статус тестирования'}), 51: ('wagtail.blocks.StructBlock', [[('name', 48), ('version', 49), ('tested', 50), ('description', 13)]], {}), 52: ('wagtail.blocks.ListBlock', (51,), {'label': 'Список конфигураций'}), 53: ('wagtail.blocks.StructBlock', [[('title', 47), ('items', 52)]], {}), 54: ('wagtail.blocks.CharBlock', (), {'default': 'Системные требования', 'label': 'Заголовок блока требований', 'required': True}), 55: ('wagtail.blocks.CharBlock', (), {'label': 'Категория (например, Платформа, ОС)', 'required': True}), 56: ('wagtail.blocks.RichTextBlock', (), {'label': 'Требования', 'required': True}), 57: ('wagtail.blocks.StructBlock', [[('category', 55), ('requirement', 56)]], {}), 58: ('wagtail.blocks.ListBlock', (57,), {'label': 'Список требований'}), 59: ('wagtail.blocks.StructBlock', [[('title', 54), ('items', 58)]], {})}, verbose_name='Блоки страницы')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Сервис 1С',
                'verbose_name_plural': 'Сервисы 1С',
            },
            bases=('wagtailcore.page',),
        ),
    ]
