# Generated by Django 5.2.7 on 2025-10-20 11:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programsindexpage',
            name='featured_manufacturers',
            field=wagtail.fields.StreamField([('manufacturer', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название производителя'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Текст'}), 2: ('wagtail.blocks.StructBlock', [[('content', 1)]], {'label': 'Краткое описание'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Логотип'}), 4: ('wagtail.blocks.StructBlock', [[('content', 1)]], {}), 5: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка на категорию продуктов', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('name', 0), ('description', 2), ('image', 3), ('text', 4), ('link', 5)]], {})}, verbose_name='Выделенные производители'),
        ),
    ]
