# Generated by Django 5.2.7 on 2025-10-20 12:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_programsindexpage_featured_manufacturers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programsindexpage',
            name='featured_manufacturers',
            field=wagtail.fields.StreamField([('manufacturer', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название производителя'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Текст'}), 2: ('wagtail.blocks.StructBlock', [[('content', 1)]], {'label': 'Краткое описание'}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('description', 2)]], {})}, verbose_name='Выделенные производители'),
        ),
    ]
