# Generated by Django 5.2.7 on 2025-10-20 12:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_programsindexpage_featured_manufacturers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programsindexpage',
            name='featured_manufacturers',
            field=wagtail.fields.StreamField([('manufacturer', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название производителя'}), 1: ('wagtail.blocks.StructBlock', [[('name', 0)]], {})}, verbose_name='Выделенные производители'),
        ),
    ]
