# Generated by Django 5.2.7 on 2025-10-20 12:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_alter_programsindexpage_featured_manufacturers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programsindexpage',
            name='featured_manufacturers',
            field=wagtail.fields.StreamField([('manufacturer', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название производителя'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Логотип', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка на категорию продуктов', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('image', 1), ('link', 2)]], {})}, verbose_name='Выделенные производители'),
        ),
    ]
