# Generated by Django 5.2.7 on 2025-10-21 10:30

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_alter_programsindexpage_featured_manufacturers'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleprogrampage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='singleprogrampage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='programcategorypage',
            name='items_per_page',
        ),
        migrations.AlterField(
            model_name='programcategorypage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Введение'),
        ),
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Краткое описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('currency', models.CharField(default='₽', max_length=10, verbose_name='Валюта')),
                ('buy_link', models.URLField(blank=True, verbose_name='Ссылка на покупку')),
                ('detailed_content', wagtail.fields.StreamField([('content', 6)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'label': 'Параграф'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок раздела', 'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Документ', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 1), ('description', 2), ('image', 3), ('document', 4)]], {'label': 'Особенность'}), 6: ('wagtail.blocks.StreamBlock', [[('paragraph', 0), ('feature', 5)]], {})}, verbose_name='Детальное содержание')),
                ('features', wagtail.fields.StreamField([('feature', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок раздела', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Документ', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2), ('document', 3)]], {})}, verbose_name='Особенности')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SubCategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Введение')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение подкатегории')),
            ],
            options={
                'verbose_name': 'Подкатегория программ',
                'verbose_name_plural': 'Подкатегории программ',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='ProgramsIndexPage',
        ),
        migrations.DeleteModel(
            name='SingleProgramPage',
        ),
    ]
