# Generated by Django 5.2.7 on 2025-10-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_remove_singleprogrampage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, verbose_name='Производитель'),
        ),
    ]
