# Generated by Django 5.2.7 on 2025-10-21 12:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_productpage_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='comparison_table',
            field=wagtail.fields.StreamField([('comparison', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Функция', 'required': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'label': 'ПРОФ', 'required': False}), 2: ('wagtail.blocks.BooleanBlock', (), {'label': 'КОРП', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'label': 'Для гос. учреждений', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('feature', 0), ('prof', 1), ('corp', 2), ('gov', 3)]], {})}, verbose_name='Таблица сравнения'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='licenses',
            field=wagtail.fields.StreamField([('license', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название лицензии', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'default': '₽', 'label': 'Валюта', 'max_length': 10}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например, USB, Электронная поставка', 'label': 'Тип лицензии', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('currency', 1), ('license_type', 2)]], {})}, verbose_name='Лицензии'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='detailed_content',
            field=wagtail.fields.StreamField([('content', 15)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'label': 'Параграф'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок особенности', 'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Документ', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 1), ('description', 2), ('image', 3), ('document', 4)]], {'label': 'Особенность'}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Название лицензии', 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'default': '₽', 'label': 'Валюта', 'max_length': 10}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например, USB, Электронная поставка', 'label': 'Тип лицензии', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('name', 6), ('currency', 7), ('license_type', 8)]], {'label': 'Лицензия'}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Функция', 'required': True}), 11: ('wagtail.blocks.BooleanBlock', (), {'label': 'ПРОФ', 'required': False}), 12: ('wagtail.blocks.BooleanBlock', (), {'label': 'КОРП', 'required': False}), 13: ('wagtail.blocks.BooleanBlock', (), {'label': 'Для гос. учреждений', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('feature', 10), ('prof', 11), ('corp', 12), ('gov', 13)]], {'label': 'Таблица сравнения'}), 15: ('wagtail.blocks.StreamBlock', [[('paragraph', 0), ('feature', 5), ('license', 9), ('comparison_table', 14)]], {})}, verbose_name='Детальное содержание'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='features',
            field=wagtail.fields.StreamField([('feature', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок особенности', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Документ', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2), ('document', 3)]], {})}, verbose_name='Особенности'),
        ),
    ]
