# Generated by Django 5.2.7 on 2025-10-21 12:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_productpage_comparison_table_productpage_licenses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpage',
            name='comparison_table',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='licenses',
        ),
        migrations.AlterField(
            model_name='productpage',
            name='detailed_content',
            field=wagtail.fields.StreamField([('content', 6)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'label': 'Параграф'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок раздела', 'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Документ', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 1), ('description', 2), ('image', 3), ('document', 4)]], {'label': 'Особенность'}), 6: ('wagtail.blocks.StreamBlock', [[('paragraph', 0), ('feature', 5)]], {})}, verbose_name='Детальное содержание'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='features',
            field=wagtail.fields.StreamField([('feature', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок раздела', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Документ', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2), ('document', 3)]], {})}, verbose_name='Особенности'),
        ),
    ]
